// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kernel_cholesky_0_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_Pipeline_sum_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln59,
        sext_ln59_1,
        j,
        empty,
        L_internal_re_load,
        L_internal_re_1_load,
        L_internal_re_2_load,
        L_internal_im_load,
        L_internal_im_1_load,
        L_internal_im_2_load,
        zext_ln477,
        product_sum_re_2_out,
        product_sum_re_2_out_ap_vld,
        product_sum_im_2_out,
        product_sum_im_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [30:0] sext_ln59;
input  [30:0] sext_ln59_1;
input  [0:0] j;
input  [1:0] empty;
input  [15:0] L_internal_re_load;
input  [15:0] L_internal_re_1_load;
input  [15:0] L_internal_re_2_load;
input  [15:0] L_internal_im_load;
input  [15:0] L_internal_im_1_load;
input  [15:0] L_internal_im_2_load;
input  [0:0] zext_ln477;
output  [31:0] product_sum_re_2_out;
output   product_sum_re_2_out_ap_vld;
output  [31:0] product_sum_im_2_out;
output   product_sum_im_2_out_ap_vld;

reg ap_idle;
reg product_sum_re_2_out_ap_vld;
reg product_sum_im_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] xor_ln481_1_fu_226_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] k_reg_186;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] zext_ln477_cast_fu_196_p1;
reg   [1:0] zext_ln477_cast_reg_844;
wire   [1:0] j_cast_fu_200_p1;
reg   [1:0] j_cast_reg_849;
wire   [1:0] zext_ln481_fu_222_p1;
reg   [1:0] zext_ln481_reg_854;
reg   [0:0] xor_ln481_1_reg_860;
reg   [0:0] xor_ln481_1_reg_860_pp0_iter1_reg;
reg   [0:0] xor_ln481_1_reg_860_pp0_iter2_reg;
reg   [0:0] xor_ln481_1_reg_860_pp0_iter3_reg;
reg   [0:0] xor_ln481_1_reg_860_pp0_iter4_reg;
wire   [0:0] xor_ln481_fu_232_p2;
wire   [15:0] tmp_re_5_fu_276_p2;
reg   [15:0] tmp_re_5_reg_869;
wire   [15:0] tmp_im_5_fu_282_p2;
reg   [15:0] tmp_im_5_reg_874;
wire   [15:0] tmp_re_2_fu_303_p3;
reg   [15:0] tmp_re_2_reg_879;
wire   [15:0] sub_ln345_fu_315_p2;
reg   [15:0] sub_ln345_reg_884;
wire   [31:0] mul_ln99_fu_327_p2;
reg   [31:0] mul_ln99_reg_889;
reg   [15:0] tmp1_reg_895;
reg   [15:0] tmp1_reg_895_pp0_iter3_reg;
wire   [13:0] trunc_ln99_fu_343_p1;
reg   [13:0] trunc_ln99_reg_900;
wire   [31:0] mul_ln100_fu_353_p2;
reg   [31:0] mul_ln100_reg_905;
reg   [15:0] tmp2_reg_911;
reg   [15:0] tmp2_reg_911_pp0_iter3_reg;
wire   [13:0] trunc_ln100_fu_369_p1;
reg   [13:0] trunc_ln100_reg_916;
wire   [31:0] mul_ln101_fu_373_p2;
reg   [31:0] mul_ln101_reg_921;
reg   [15:0] tmp3_reg_927;
reg   [15:0] tmp3_reg_927_pp0_iter3_reg;
wire   [13:0] trunc_ln101_fu_389_p1;
reg   [13:0] trunc_ln101_reg_932;
wire   [31:0] mul_ln102_fu_393_p2;
reg   [31:0] mul_ln102_reg_937;
reg   [15:0] tmp4_reg_943;
reg   [15:0] tmp4_reg_943_pp0_iter3_reg;
wire   [13:0] trunc_ln102_fu_409_p1;
reg   [13:0] trunc_ln102_reg_948;
wire   [1:0] add_ln103_fu_557_p2;
reg   [1:0] add_ln103_reg_953;
wire   [1:0] add_ln103_3_fu_563_p2;
reg   [1:0] add_ln103_3_reg_958;
wire   [15:0] tmp5_re_fu_576_p2;
reg   [15:0] tmp5_re_reg_963;
wire   [15:0] tmp5_im_fu_589_p2;
reg   [15:0] tmp5_im_reg_968;
reg   [0:0] ap_phi_mux_k_phi_fu_189_p4;
wire    ap_loop_init;
reg   [31:0] tmp2_im_1_fu_98;
wire   [31:0] tmp2_im_4_fu_763_p3;
wire  signed [31:0] sext_ln59_1_cast_fu_204_p1;
wire    ap_block_pp0_stage0;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [31:0] tmp2_re_fu_102;
wire   [31:0] tmp2_re_5_fu_689_p3;
wire  signed [31:0] sext_ln59_cast_fu_208_p1;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] tmp_re_fu_242_p7;
wire   [1:0] add_ln484_fu_238_p2;
wire   [15:0] tmp_im_fu_259_p7;
wire   [15:0] tmp_re_fu_242_p9;
wire   [15:0] tmp_im_fu_259_p9;
wire   [1:0] add_ln484_2_fu_288_p2;
wire   [1:0] add_ln484_1_fu_292_p2;
wire   [0:0] icmp_ln352_fu_297_p2;
wire   [15:0] tmp_im_2_fu_309_p3;
wire  signed [15:0] mul_ln99_fu_327_p0;
wire  signed [31:0] sext_ln99_1_fu_324_p1;
wire  signed [15:0] mul_ln99_fu_327_p1;
wire  signed [31:0] sext_ln99_fu_321_p1;
wire  signed [15:0] mul_ln100_fu_353_p0;
wire  signed [31:0] sext_ln100_1_fu_350_p1;
wire  signed [15:0] mul_ln100_fu_353_p1;
wire  signed [31:0] sext_ln100_fu_347_p1;
wire  signed [15:0] mul_ln101_fu_373_p0;
wire  signed [15:0] mul_ln101_fu_373_p1;
wire  signed [15:0] mul_ln102_fu_393_p0;
wire  signed [15:0] mul_ln102_fu_393_p1;
wire   [0:0] tmp_2_fu_425_p3;
wire   [0:0] icmp_ln99_fu_420_p2;
wire   [0:0] or_ln99_fu_432_p2;
wire   [0:0] tmp_1_fu_413_p3;
wire   [0:0] and_ln99_fu_438_p2;
wire   [0:0] tmp_4_fu_460_p3;
wire   [0:0] icmp_ln100_fu_455_p2;
wire   [0:0] or_ln100_fu_467_p2;
wire   [0:0] tmp_3_fu_448_p3;
wire   [0:0] tmp_6_fu_491_p3;
wire   [0:0] icmp_ln101_fu_486_p2;
wire   [0:0] or_ln101_fu_498_p2;
wire   [0:0] tmp_5_fu_479_p3;
wire   [0:0] and_ln101_fu_504_p2;
wire   [0:0] tmp_8_fu_526_p3;
wire   [0:0] icmp_ln102_fu_521_p2;
wire   [0:0] or_ln102_fu_533_p2;
wire   [0:0] tmp_7_fu_514_p3;
wire   [0:0] and_ln102_fu_539_p2;
wire   [0:0] and_ln100_fu_473_p2;
wire   [1:0] zext_ln100_fu_444_p1;
wire   [1:0] select_ln100_fu_549_p3;
wire   [1:0] zext_ln102_fu_510_p1;
wire   [1:0] and_ln102_cast_fu_545_p1;
wire  signed [15:0] sext_ln103_fu_573_p1;
wire   [15:0] tmp2_2_fu_569_p2;
wire   [15:0] zext_ln103_fu_586_p1;
wire   [15:0] add_ln103_2_fu_582_p2;
wire  signed [30:0] tmp2_re_4_fu_601_p3;
wire  signed [30:0] tmp2_im_3_fu_612_p3;
wire  signed [31:0] sext_ln180_fu_623_p0;
wire  signed [31:0] sext_ln59_2_fu_608_p1;
wire  signed [31:0] add_ln180_1_fu_631_p1;
wire  signed [32:0] sext_ln180_1_fu_627_p1;
wire  signed [32:0] sext_ln180_fu_623_p1;
wire   [32:0] add_ln180_fu_637_p2;
wire   [31:0] add_ln180_1_fu_631_p2;
wire   [0:0] tmp_9_fu_643_p3;
wire   [0:0] tmp_10_fu_655_p3;
wire   [0:0] xor_ln180_fu_663_p2;
wire   [0:0] and_ln180_fu_669_p2;
wire   [0:0] xor_ln180_1_fu_675_p2;
wire   [31:0] select_ln180_fu_681_p3;
wire   [31:0] tmp2_re_2_fu_651_p1;
wire  signed [31:0] sext_ln181_fu_697_p0;
wire  signed [31:0] sext_ln59_3_fu_619_p1;
wire  signed [31:0] add_ln181_1_fu_705_p1;
wire  signed [32:0] sext_ln181_1_fu_701_p1;
wire  signed [32:0] sext_ln181_fu_697_p1;
wire   [32:0] add_ln181_fu_711_p2;
wire   [31:0] add_ln181_1_fu_705_p2;
wire   [0:0] tmp_11_fu_717_p3;
wire   [0:0] tmp_12_fu_729_p3;
wire   [0:0] xor_ln181_fu_737_p2;
wire   [0:0] and_ln181_fu_743_p2;
wire   [0:0] xor_ln181_1_fu_749_p2;
wire   [31:0] select_ln181_fu_755_p3;
wire   [31:0] tmp2_im_fu_725_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_re_fu_242_p1;
wire  signed [1:0] tmp_re_fu_242_p3;
wire  signed [1:0] tmp_re_fu_242_p5;
wire   [1:0] tmp_im_fu_259_p1;
wire  signed [1:0] tmp_im_fu_259_p3;
wire  signed [1:0] tmp_im_fu_259_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 tmp2_im_1_fu_98 = 32'd0;
#0 tmp2_re_fu_102 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) kernel_cholesky_0_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U4(
    .din0(L_internal_re_load),
    .din1(L_internal_re_1_load),
    .din2(L_internal_re_2_load),
    .def(tmp_re_fu_242_p7),
    .sel(add_ln484_fu_238_p2),
    .dout(tmp_re_fu_242_p9)
);

(* dissolve_hierarchy = "yes" *) kernel_cholesky_0_sparsemux_7_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_7_2_16_1_1_U5(
    .din0(L_internal_im_load),
    .din1(L_internal_im_1_load),
    .din2(L_internal_im_2_load),
    .def(tmp_im_fu_259_p7),
    .sel(add_ln484_fu_238_p2),
    .dout(tmp_im_fu_259_p9)
);

kernel_cholesky_0_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U6(
    .din0(mul_ln99_fu_327_p0),
    .din1(mul_ln99_fu_327_p1),
    .dout(mul_ln99_fu_327_p2)
);

kernel_cholesky_0_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U7(
    .din0(mul_ln100_fu_353_p0),
    .din1(mul_ln100_fu_353_p1),
    .dout(mul_ln100_fu_353_p2)
);

kernel_cholesky_0_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U8(
    .din0(mul_ln101_fu_373_p0),
    .din1(mul_ln101_fu_373_p1),
    .dout(mul_ln101_fu_373_p2)
);

kernel_cholesky_0_mul_16s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16s_32_1_1_U9(
    .din0(mul_ln102_fu_393_p0),
    .din1(mul_ln102_fu_393_p1),
    .dout(mul_ln102_fu_393_p2)
);

kernel_cholesky_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            tmp2_im_1_fu_98 <= sext_ln59_1_cast_fu_204_p1;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (xor_ln481_1_reg_860_pp0_iter4_reg == 1'd1))) begin
            tmp2_im_1_fu_98 <= tmp2_im_4_fu_763_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            tmp2_re_fu_102 <= sext_ln59_cast_fu_208_p1;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (xor_ln481_1_reg_860_pp0_iter4_reg == 1'd1))) begin
            tmp2_re_fu_102 <= tmp2_re_5_fu_689_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln103_3_reg_958 <= add_ln103_3_fu_563_p2;
        add_ln103_reg_953 <= add_ln103_fu_557_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        mul_ln100_reg_905 <= mul_ln100_fu_353_p2;
        mul_ln101_reg_921 <= mul_ln101_fu_373_p2;
        mul_ln102_reg_937 <= mul_ln102_fu_393_p2;
        mul_ln99_reg_889 <= mul_ln99_fu_327_p2;
        tmp1_reg_895 <= {{mul_ln99_fu_327_p2[30:15]}};
        tmp1_reg_895_pp0_iter3_reg <= tmp1_reg_895;
        tmp2_reg_911 <= {{mul_ln100_fu_353_p2[30:15]}};
        tmp2_reg_911_pp0_iter3_reg <= tmp2_reg_911;
        tmp3_reg_927 <= {{mul_ln101_fu_373_p2[30:15]}};
        tmp3_reg_927_pp0_iter3_reg <= tmp3_reg_927;
        tmp4_reg_943 <= {{mul_ln102_fu_393_p2[30:15]}};
        tmp4_reg_943_pp0_iter3_reg <= tmp4_reg_943;
        tmp5_im_reg_968 <= tmp5_im_fu_589_p2;
        tmp5_re_reg_963 <= tmp5_re_fu_576_p2;
        trunc_ln100_reg_916 <= trunc_ln100_fu_369_p1;
        trunc_ln101_reg_932 <= trunc_ln101_fu_389_p1;
        trunc_ln102_reg_948 <= trunc_ln102_fu_409_p1;
        trunc_ln99_reg_900 <= trunc_ln99_fu_343_p1;
        xor_ln481_1_reg_860_pp0_iter2_reg <= xor_ln481_1_reg_860_pp0_iter1_reg;
        xor_ln481_1_reg_860_pp0_iter3_reg <= xor_ln481_1_reg_860_pp0_iter2_reg;
        xor_ln481_1_reg_860_pp0_iter4_reg <= xor_ln481_1_reg_860_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        j_cast_reg_849[0] <= j_cast_fu_200_p1[0];
        sub_ln345_reg_884 <= sub_ln345_fu_315_p2;
        tmp_im_5_reg_874 <= tmp_im_5_fu_282_p2;
        tmp_re_2_reg_879 <= tmp_re_2_fu_303_p3;
        tmp_re_5_reg_869 <= tmp_re_5_fu_276_p2;
        xor_ln481_1_reg_860 <= xor_ln481_1_fu_226_p2;
        xor_ln481_1_reg_860_pp0_iter1_reg <= xor_ln481_1_reg_860;
        zext_ln477_cast_reg_844[0] <= zext_ln477_cast_fu_196_p1[0];
        zext_ln481_reg_854[0] <= zext_ln481_fu_222_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if (((xor_ln481_1_fu_226_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_reg_186 <= xor_ln481_fu_232_p2;
    end
end

always @ (*) begin
    if (((xor_ln481_1_fu_226_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_phi_mux_k_phi_fu_189_p4 = 1'd0;
    end else begin
        ap_phi_mux_k_phi_fu_189_p4 = k_reg_186;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (xor_ln481_1_reg_860_pp0_iter3_reg == 1'd0))) begin
        product_sum_im_2_out_ap_vld = 1'b1;
    end else begin
        product_sum_im_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (xor_ln481_1_reg_860_pp0_iter3_reg == 1'd0))) begin
        product_sum_re_2_out_ap_vld = 1'b1;
    end else begin
        product_sum_re_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_2_fu_582_p2 = (tmp3_reg_927_pp0_iter3_reg + tmp4_reg_943_pp0_iter3_reg);

assign add_ln103_3_fu_563_p2 = (zext_ln102_fu_510_p1 + and_ln102_cast_fu_545_p1);

assign add_ln103_fu_557_p2 = (zext_ln100_fu_444_p1 + select_ln100_fu_549_p3);

assign add_ln180_1_fu_631_p1 = tmp2_re_fu_102;

assign add_ln180_1_fu_631_p2 = ($signed(sext_ln59_2_fu_608_p1) + $signed(add_ln180_1_fu_631_p1));

assign add_ln180_fu_637_p2 = ($signed(sext_ln180_1_fu_627_p1) + $signed(sext_ln180_fu_623_p1));

assign add_ln181_1_fu_705_p1 = tmp2_im_1_fu_98;

assign add_ln181_1_fu_705_p2 = ($signed(sext_ln59_3_fu_619_p1) + $signed(add_ln181_1_fu_705_p1));

assign add_ln181_fu_711_p2 = ($signed(sext_ln181_1_fu_701_p1) + $signed(sext_ln181_fu_697_p1));

assign add_ln484_1_fu_292_p2 = (add_ln484_2_fu_288_p2 + zext_ln481_reg_854);

assign add_ln484_2_fu_288_p2 = (j_cast_reg_849 + zext_ln477_cast_reg_844);

assign add_ln484_fu_238_p2 = (zext_ln481_reg_854 + empty);

assign and_ln100_fu_473_p2 = (tmp_3_fu_448_p3 & or_ln100_fu_467_p2);

assign and_ln101_fu_504_p2 = (tmp_5_fu_479_p3 & or_ln101_fu_498_p2);

assign and_ln102_cast_fu_545_p1 = and_ln102_fu_539_p2;

assign and_ln102_fu_539_p2 = (tmp_7_fu_514_p3 & or_ln102_fu_533_p2);

assign and_ln180_fu_669_p2 = (xor_ln180_fu_663_p2 & tmp_10_fu_655_p3);

assign and_ln181_fu_743_p2 = (xor_ln181_fu_737_p2 & tmp_12_fu_729_p3);

assign and_ln99_fu_438_p2 = (tmp_1_fu_413_p3 & or_ln99_fu_432_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln100_fu_455_p2 = ((trunc_ln100_reg_916 != 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln101_fu_486_p2 = ((trunc_ln101_reg_932 != 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_521_p2 = ((trunc_ln102_reg_948 != 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln352_fu_297_p2 = ((add_ln484_1_fu_292_p2 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_420_p2 = ((trunc_ln99_reg_900 != 14'd0) ? 1'b1 : 1'b0);

assign j_cast_fu_200_p1 = j;

assign mul_ln100_fu_353_p0 = sext_ln100_1_fu_350_p1;

assign mul_ln100_fu_353_p1 = sext_ln100_fu_347_p1;

assign mul_ln101_fu_373_p0 = sext_ln100_1_fu_350_p1;

assign mul_ln101_fu_373_p1 = sext_ln99_fu_321_p1;

assign mul_ln102_fu_393_p0 = sext_ln99_1_fu_324_p1;

assign mul_ln102_fu_393_p1 = sext_ln100_fu_347_p1;

assign mul_ln99_fu_327_p0 = sext_ln99_1_fu_324_p1;

assign mul_ln99_fu_327_p1 = sext_ln99_fu_321_p1;

assign or_ln100_fu_467_p2 = (tmp_4_fu_460_p3 | icmp_ln100_fu_455_p2);

assign or_ln101_fu_498_p2 = (tmp_6_fu_491_p3 | icmp_ln101_fu_486_p2);

assign or_ln102_fu_533_p2 = (tmp_8_fu_526_p3 | icmp_ln102_fu_521_p2);

assign or_ln99_fu_432_p2 = (tmp_2_fu_425_p3 | icmp_ln99_fu_420_p2);

assign product_sum_im_2_out = tmp2_im_1_fu_98;

assign product_sum_re_2_out = tmp2_re_fu_102;

assign select_ln100_fu_549_p3 = ((and_ln100_fu_473_p2[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln180_fu_681_p3 = ((and_ln180_fu_669_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln181_fu_755_p3 = ((and_ln181_fu_743_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign sext_ln100_1_fu_350_p1 = $signed(sub_ln345_reg_884);

assign sext_ln100_fu_347_p1 = $signed(tmp_im_5_reg_874);

assign sext_ln103_fu_573_p1 = $signed(add_ln103_reg_953);

assign sext_ln180_1_fu_627_p1 = tmp2_re_4_fu_601_p3;

assign sext_ln180_fu_623_p0 = tmp2_re_fu_102;

assign sext_ln180_fu_623_p1 = sext_ln180_fu_623_p0;

assign sext_ln181_1_fu_701_p1 = tmp2_im_3_fu_612_p3;

assign sext_ln181_fu_697_p0 = tmp2_im_1_fu_98;

assign sext_ln181_fu_697_p1 = sext_ln181_fu_697_p0;

assign sext_ln59_1_cast_fu_204_p1 = $signed(sext_ln59_1);

assign sext_ln59_2_fu_608_p1 = tmp2_re_4_fu_601_p3;

assign sext_ln59_3_fu_619_p1 = tmp2_im_3_fu_612_p3;

assign sext_ln59_cast_fu_208_p1 = $signed(sext_ln59);

assign sext_ln99_1_fu_324_p1 = $signed(tmp_re_2_reg_879);

assign sext_ln99_fu_321_p1 = $signed(tmp_re_5_reg_869);

assign sub_ln345_fu_315_p2 = (16'd0 - tmp_im_2_fu_309_p3);

assign tmp2_2_fu_569_p2 = (tmp1_reg_895_pp0_iter3_reg - tmp2_reg_911_pp0_iter3_reg);

assign tmp2_im_3_fu_612_p3 = {{tmp5_im_reg_968}, {15'd0}};

assign tmp2_im_4_fu_763_p3 = ((xor_ln181_1_fu_749_p2[0:0] == 1'b1) ? select_ln181_fu_755_p3 : tmp2_im_fu_725_p1);

assign tmp2_im_fu_725_p1 = add_ln181_fu_711_p2[31:0];

assign tmp2_re_2_fu_651_p1 = add_ln180_fu_637_p2[31:0];

assign tmp2_re_4_fu_601_p3 = {{tmp5_re_reg_963}, {15'd0}};

assign tmp2_re_5_fu_689_p3 = ((xor_ln180_1_fu_675_p2[0:0] == 1'b1) ? select_ln180_fu_681_p3 : tmp2_re_2_fu_651_p1);

assign tmp5_im_fu_589_p2 = (zext_ln103_fu_586_p1 + add_ln103_2_fu_582_p2);

assign tmp5_re_fu_576_p2 = ($signed(sext_ln103_fu_573_p1) + $signed(tmp2_2_fu_569_p2));

assign tmp_10_fu_655_p3 = add_ln180_1_fu_631_p2[32'd31];

assign tmp_11_fu_717_p3 = add_ln181_fu_711_p2[32'd32];

assign tmp_12_fu_729_p3 = add_ln181_1_fu_705_p2[32'd31];

assign tmp_1_fu_413_p3 = mul_ln99_reg_889[32'd14];

assign tmp_2_fu_425_p3 = mul_ln99_reg_889[32'd15];

assign tmp_3_fu_448_p3 = mul_ln100_reg_905[32'd14];

assign tmp_4_fu_460_p3 = mul_ln100_reg_905[32'd15];

assign tmp_5_fu_479_p3 = mul_ln101_reg_921[32'd14];

assign tmp_6_fu_491_p3 = mul_ln101_reg_921[32'd15];

assign tmp_7_fu_514_p3 = mul_ln102_reg_937[32'd14];

assign tmp_8_fu_526_p3 = mul_ln102_reg_937[32'd15];

assign tmp_9_fu_643_p3 = add_ln180_fu_637_p2[32'd32];

assign tmp_im_2_fu_309_p3 = ((icmp_ln352_fu_297_p2[0:0] == 1'b1) ? L_internal_im_1_load : L_internal_im_load);

assign tmp_im_5_fu_282_p2 = (16'd0 - tmp_im_fu_259_p9);

assign tmp_im_fu_259_p7 = 'bx;

assign tmp_re_2_fu_303_p3 = ((icmp_ln352_fu_297_p2[0:0] == 1'b1) ? L_internal_re_1_load : L_internal_re_load);

assign tmp_re_5_fu_276_p2 = (16'd0 - tmp_re_fu_242_p9);

assign tmp_re_fu_242_p7 = 'bx;

assign trunc_ln100_fu_369_p1 = mul_ln100_fu_353_p2[13:0];

assign trunc_ln101_fu_389_p1 = mul_ln101_fu_373_p2[13:0];

assign trunc_ln102_fu_409_p1 = mul_ln102_fu_393_p2[13:0];

assign trunc_ln99_fu_343_p1 = mul_ln99_fu_327_p2[13:0];

assign xor_ln180_1_fu_675_p2 = (tmp_9_fu_643_p3 ^ tmp_10_fu_655_p3);

assign xor_ln180_fu_663_p2 = (tmp_9_fu_643_p3 ^ 1'd1);

assign xor_ln181_1_fu_749_p2 = (tmp_12_fu_729_p3 ^ tmp_11_fu_717_p3);

assign xor_ln181_fu_737_p2 = (tmp_11_fu_717_p3 ^ 1'd1);

assign xor_ln481_1_fu_226_p2 = (j ^ ap_phi_mux_k_phi_fu_189_p4);

assign xor_ln481_fu_232_p2 = (ap_phi_mux_k_phi_fu_189_p4 ^ 1'd1);

assign zext_ln100_fu_444_p1 = and_ln99_fu_438_p2;

assign zext_ln102_fu_510_p1 = and_ln101_fu_504_p2;

assign zext_ln103_fu_586_p1 = add_ln103_3_reg_958;

assign zext_ln477_cast_fu_196_p1 = zext_ln477;

assign zext_ln481_fu_222_p1 = ap_phi_mux_k_phi_fu_189_p4;

always @ (posedge ap_clk) begin
    zext_ln477_cast_reg_844[1] <= 1'b0;
    j_cast_reg_849[1] <= 1'b0;
    zext_ln481_reg_854[1] <= 1'b0;
end

endmodule //kernel_cholesky_0_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_Pipeline_sum_s
