#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("keyStrm_dout", 32, hls_in, 0, "ap_fifo", "fifo_data_in", 1),
	Port_Property("keyStrm_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("keyStrm_read", 1, hls_out, 0, "ap_fifo", "fifo_port_we", 1),
	Port_Property("msgStrm_dout", 32, hls_in, 1, "ap_fifo", "fifo_data_in", 1),
	Port_Property("msgStrm_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("msgStrm_read", 1, hls_out, 1, "ap_fifo", "fifo_port_we", 1),
	Port_Property("lenStrm_dout", 64, hls_in, 2, "ap_fifo", "fifo_data_in", 1),
	Port_Property("lenStrm_empty_n", 1, hls_in, 2, "ap_fifo", "fifo_status", 1),
	Port_Property("lenStrm_read", 1, hls_out, 2, "ap_fifo", "fifo_port_we", 1),
	Port_Property("eLenStrm_dout", 1, hls_in, 3, "ap_fifo", "fifo_data_in", 1),
	Port_Property("eLenStrm_empty_n", 1, hls_in, 3, "ap_fifo", "fifo_status", 1),
	Port_Property("eLenStrm_read", 1, hls_out, 3, "ap_fifo", "fifo_port_we", 1),
	Port_Property("hshStrm_din", 256, hls_out, 4, "ap_fifo", "fifo_data_in", 1),
	Port_Property("hshStrm_full_n", 1, hls_in, 4, "ap_fifo", "fifo_status", 1),
	Port_Property("hshStrm_write", 1, hls_out, 4, "ap_fifo", "fifo_port_we", 1),
	Port_Property("eHshStrm_din", 1, hls_out, 5, "ap_fifo", "fifo_data_in", 1),
	Port_Property("eHshStrm_full_n", 1, hls_in, 5, "ap_fifo", "fifo_status", 1),
	Port_Property("eHshStrm_write", 1, hls_out, 5, "ap_fifo", "fifo_port_we", 1),
};
const char* HLS_Design_Meta::dut_name = "test_hmac_sha256";
