// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_cholesky_0_kernel_cholesky_0,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.280813,HLS_SYN_LAT=256,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3469,HLS_SYN_LUT=6158,HLS_VERSION=2024_2}" *)

module kernel_cholesky_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        matrixAStrm_dout,
        matrixAStrm_empty_n,
        matrixAStrm_read,
        matrixLStrm_din,
        matrixLStrm_full_n,
        matrixLStrm_write,
        ap_return
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] matrixAStrm_dout;
input   matrixAStrm_empty_n;
output   matrixAStrm_read;
output  [31:0] matrixLStrm_din;
input   matrixLStrm_full_n;
output   matrixLStrm_write;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_return;
reg   [31:0] ret_reg_70;
wire    ap_CS_fsm_state4;
reg   [3:0] A_re_address0;
reg    A_re_ce0;
reg    A_re_we0;
wire   [15:0] A_re_q0;
reg   [3:0] A_im_address0;
reg    A_im_ce0;
reg    A_im_we0;
wire   [15:0] A_im_q0;
reg   [3:0] L_re_address0;
reg    L_re_ce0;
reg    L_re_we0;
wire   [15:0] L_re_q0;
reg    L_re_ce1;
reg    L_re_we1;
reg   [3:0] L_im_address0;
reg    L_im_ce0;
reg    L_im_we0;
wire   [15:0] L_im_q0;
reg    L_im_ce1;
reg    L_im_we1;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_done;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_idle;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_ready;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_matrixAStrm_read;
wire   [3:0] grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_address0;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_ce0;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_we0;
wire   [15:0] grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_d0;
wire   [3:0] grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_address0;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_ce0;
wire    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_we0;
wire   [15:0] grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_d0;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_done;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_idle;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_ready;
wire   [3:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_re_address0;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_re_ce0;
wire   [3:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_im_address0;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_im_ce0;
wire   [3:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_address0;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_ce0;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_we0;
wire   [15:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_d0;
wire   [3:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_address1;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_ce1;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_we1;
wire   [15:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_d1;
wire   [3:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_address0;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_ce0;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_we0;
wire   [15:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_d0;
wire   [3:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_address1;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_ce1;
wire    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_we1;
wire   [15:0] grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_d1;
wire    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start;
wire    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_done;
wire    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_idle;
wire    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_ready;
wire   [31:0] grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_matrixLStrm_din;
wire    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_matrixLStrm_write;
wire   [3:0] grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_re_address0;
wire    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_re_ce0;
wire   [3:0] grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_im_address0;
wire    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_im_ce0;
reg    grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start_reg = 1'b0;
#0 grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start_reg = 1'b0;
#0 grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start_reg = 1'b0;
end

kernel_cholesky_0_A_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
A_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(A_re_address0),
    .ce0(A_re_ce0),
    .we0(A_re_we0),
    .d0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_d0),
    .q0(A_re_q0)
);

kernel_cholesky_0_A_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
A_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(A_im_address0),
    .ce0(A_im_ce0),
    .we0(A_im_we0),
    .d0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_d0),
    .q0(A_im_q0)
);

kernel_cholesky_0_L_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
L_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(L_re_address0),
    .ce0(L_re_ce0),
    .we0(L_re_we0),
    .d0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_d0),
    .q0(L_re_q0),
    .address1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_address1),
    .ce1(L_re_ce1),
    .we1(L_re_we1),
    .d1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_d1)
);

kernel_cholesky_0_L_re_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
L_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(L_im_address0),
    .ce0(L_im_ce0),
    .we0(L_im_we0),
    .d0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_d0),
    .q0(L_im_q0),
    .address1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_address1),
    .ce1(L_im_ce1),
    .we1(L_im_we1),
    .d1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_d1)
);

kernel_cholesky_0_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start),
    .ap_done(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_done),
    .ap_idle(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_idle),
    .ap_ready(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_ready),
    .matrixAStrm_dout(matrixAStrm_dout),
    .matrixAStrm_empty_n(matrixAStrm_empty_n),
    .matrixAStrm_read(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_matrixAStrm_read),
    .A_re_address0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_address0),
    .A_re_ce0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_ce0),
    .A_re_we0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_we0),
    .A_re_d0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_d0),
    .A_im_address0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_address0),
    .A_im_ce0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_ce0),
    .A_im_we0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_we0),
    .A_im_d0(grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_d0)
);

kernel_cholesky_0_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start),
    .ap_done(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_done),
    .ap_idle(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_idle),
    .ap_ready(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_ready),
    .A_re_address0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_re_address0),
    .A_re_ce0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_re_ce0),
    .A_re_q0(A_re_q0),
    .A_im_address0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_im_address0),
    .A_im_ce0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_im_ce0),
    .A_im_q0(A_im_q0),
    .L_re_address0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_address0),
    .L_re_ce0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_ce0),
    .L_re_we0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_we0),
    .L_re_d0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_d0),
    .L_re_address1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_address1),
    .L_re_ce1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_ce1),
    .L_re_we1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_we1),
    .L_re_d1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_d1),
    .L_im_address0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_address0),
    .L_im_ce0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_ce0),
    .L_im_we0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_we0),
    .L_im_d0(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_d0),
    .L_im_address1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_address1),
    .L_im_ce1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_ce1),
    .L_im_we1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_we1),
    .L_im_d1(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_d1),
    .ap_return(grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_return)
);

kernel_cholesky_0_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start),
    .ap_done(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_done),
    .ap_idle(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_idle),
    .ap_ready(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_ready),
    .matrixLStrm_din(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_matrixLStrm_din),
    .matrixLStrm_full_n(matrixLStrm_full_n),
    .matrixLStrm_write(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_matrixLStrm_write),
    .L_re_address0(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_re_address0),
    .L_re_ce0(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_re_ce0),
    .L_re_q0(L_re_q0),
    .L_im_address0(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_im_address0),
    .L_im_ce0(grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_im_ce0),
    .L_im_q0(L_im_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_ready == 1'b1)) begin
            grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_ready == 1'b1)) begin
            grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_ready == 1'b1)) begin
            grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ret_reg_70 <= grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_return;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_im_address0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_im_address0 = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_address0;
    end else begin
        A_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_im_ce0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_im_ce0 = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_ce0;
    end else begin
        A_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_im_we0 = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_im_we0;
    end else begin
        A_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_re_address0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_re_address0 = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_address0;
    end else begin
        A_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_re_ce0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_A_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_re_ce0 = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_ce0;
    end else begin
        A_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_re_we0 = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_A_re_we0;
    end else begin
        A_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        L_im_address0 = grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        L_im_address0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_address0;
    end else begin
        L_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        L_im_ce0 = grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        L_im_ce0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_ce0;
    end else begin
        L_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        L_im_ce1 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_ce1;
    end else begin
        L_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        L_im_we0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_we0;
    end else begin
        L_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        L_im_we1 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_im_we1;
    end else begin
        L_im_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        L_re_address0 = grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        L_re_address0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_address0;
    end else begin
        L_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        L_re_ce0 = grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_L_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        L_re_ce0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_ce0;
    end else begin
        L_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        L_re_ce1 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_ce1;
    end else begin
        L_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        L_re_we0 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_we0;
    end else begin
        L_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        L_re_we1 = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_L_re_we1;
    end else begin
        L_re_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_return = ret_reg_70;

assign grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start = grp_choleskyAlt_false_3_choleskyTraits_x_complex_x_complex_ap_fixed_s_fu_54_ap_start_reg;

assign grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_ap_start_reg;

assign grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start = grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_ap_start_reg;

assign matrixAStrm_read = grp_kernel_cholesky_0_Pipeline_read_matrix_rows_read_matrix_cols_fu_44_matrixAStrm_read;

assign matrixLStrm_din = grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_matrixLStrm_din;

assign matrixLStrm_write = grp_kernel_cholesky_0_Pipeline_write_matrix_rows_write_matrix_cols_fu_62_matrixLStrm_write;

endmodule //kernel_cholesky_0
