// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_mergeKopad_32_64_256_32_64_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        kopad2Strm_dout,
        kopad2Strm_empty_n,
        kopad2Strm_read,
        kopad2Strm_num_data_valid,
        kopad2Strm_fifo_cap,
        msgHashStrm_dout,
        msgHashStrm_empty_n,
        msgHashStrm_read,
        msgHashStrm_num_data_valid,
        msgHashStrm_fifo_cap,
        eMsgHashStrm_dout,
        eMsgHashStrm_empty_n,
        eMsgHashStrm_read,
        eMsgHashStrm_num_data_valid,
        eMsgHashStrm_fifo_cap,
        mergeKopadStrm_din,
        mergeKopadStrm_full_n,
        mergeKopadStrm_write,
        mergeKopadStrm_num_data_valid,
        mergeKopadStrm_fifo_cap,
        mergeKopadLenStrm_din,
        mergeKopadLenStrm_full_n,
        mergeKopadLenStrm_write,
        mergeKopadLenStrm_num_data_valid,
        mergeKopadLenStrm_fifo_cap,
        eMergeKopadLenStrm_din,
        eMergeKopadLenStrm_full_n,
        eMergeKopadLenStrm_write,
        eMergeKopadLenStrm_num_data_valid,
        eMergeKopadLenStrm_fifo_cap
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] kopad2Strm_dout;
input   kopad2Strm_empty_n;
output   kopad2Strm_read;
input  [2:0] kopad2Strm_num_data_valid;
input  [2:0] kopad2Strm_fifo_cap;
input  [255:0] msgHashStrm_dout;
input   msgHashStrm_empty_n;
output   msgHashStrm_read;
input  [2:0] msgHashStrm_num_data_valid;
input  [2:0] msgHashStrm_fifo_cap;
input  [0:0] eMsgHashStrm_dout;
input   eMsgHashStrm_empty_n;
output   eMsgHashStrm_read;
input  [2:0] eMsgHashStrm_num_data_valid;
input  [2:0] eMsgHashStrm_fifo_cap;
output  [31:0] mergeKopadStrm_din;
input   mergeKopadStrm_full_n;
output   mergeKopadStrm_write;
input  [31:0] mergeKopadStrm_num_data_valid;
input  [31:0] mergeKopadStrm_fifo_cap;
output  [63:0] mergeKopadLenStrm_din;
input   mergeKopadLenStrm_full_n;
output   mergeKopadLenStrm_write;
input  [2:0] mergeKopadLenStrm_num_data_valid;
input  [2:0] mergeKopadLenStrm_fifo_cap;
output  [0:0] eMergeKopadLenStrm_din;
input   eMergeKopadLenStrm_full_n;
output   eMergeKopadLenStrm_write;
input  [2:0] eMergeKopadLenStrm_num_data_valid;
input  [2:0] eMergeKopadLenStrm_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg kopad2Strm_read;
reg msgHashStrm_read;
reg eMsgHashStrm_read;
reg[31:0] mergeKopadStrm_din;
reg mergeKopadStrm_write;
reg mergeKopadLenStrm_write;
reg[0:0] eMergeKopadLenStrm_din;
reg eMergeKopadLenStrm_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    kopad2Strm_blk_n;
wire    ap_CS_fsm_state2;
reg    msgHashStrm_blk_n;
reg    eMsgHashStrm_blk_n;
reg    mergeKopadLenStrm_blk_n;
reg    eMergeKopadLenStrm_blk_n;
reg   [511:0] kopad_reg_146;
reg    ap_block_state2;
reg   [255:0] msgHash_reg_151;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_idle;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_ready;
wire   [31:0] grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm_din;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm_write;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_idle;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_ready;
wire   [31:0] grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm_din;
wire    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm_write;
reg    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg = 1'b0;
#0 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg = 1'b0;
end

test_hmac_sha256_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start),
    .ap_done(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done),
    .ap_idle(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_idle),
    .ap_ready(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_ready),
    .mergeKopadStrm_din(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm_din),
    .mergeKopadStrm_full_n(mergeKopadStrm_full_n),
    .mergeKopadStrm_write(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm_write),
    .mergeKopadStrm_num_data_valid(mergeKopadStrm_num_data_valid),
    .mergeKopadStrm_fifo_cap(mergeKopadStrm_fifo_cap),
    .kopad(kopad_reg_146)
);

test_hmac_sha256_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3 grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start),
    .ap_done(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done),
    .ap_idle(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_idle),
    .ap_ready(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_ready),
    .mergeKopadStrm_din(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm_din),
    .mergeKopadStrm_full_n(mergeKopadStrm_full_n),
    .mergeKopadStrm_write(grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm_write),
    .mergeKopadStrm_num_data_valid(mergeKopadStrm_num_data_valid),
    .mergeKopadStrm_fifo_cap(mergeKopadStrm_fifo_cap),
    .msgHash(msgHash_reg_151)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((eMsgHashStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg <= 1'b1;
        end else if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_ready == 1'b1)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_ready == 1'b1)) begin
            grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        kopad_reg_146 <= kopad2Strm_dout;
        msgHash_reg_151 <= msgHashStrm_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((eMsgHashStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        eMergeKopadLenStrm_blk_n = eMergeKopadLenStrm_full_n;
    end else begin
        eMergeKopadLenStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        if ((eMsgHashStrm_dout == 1'd1)) begin
            eMergeKopadLenStrm_din = 1'd1;
        end else if ((eMsgHashStrm_dout == 1'd0)) begin
            eMergeKopadLenStrm_din = 1'd0;
        end else begin
            eMergeKopadLenStrm_din = 'bx;
        end
    end else begin
        eMergeKopadLenStrm_din = 'bx;
    end
end

always @ (*) begin
    if ((((eMsgHashStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2)) | ((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2)))) begin
        eMergeKopadLenStrm_write = 1'b1;
    end else begin
        eMergeKopadLenStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        eMsgHashStrm_blk_n = eMsgHashStrm_empty_n;
    end else begin
        eMsgHashStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        eMsgHashStrm_read = 1'b1;
    end else begin
        eMsgHashStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        kopad2Strm_blk_n = kopad2Strm_empty_n;
    end else begin
        kopad2Strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        kopad2Strm_read = 1'b1;
    end else begin
        kopad2Strm_read = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mergeKopadLenStrm_blk_n = mergeKopadLenStrm_full_n;
    end else begin
        mergeKopadLenStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        mergeKopadLenStrm_write = 1'b1;
    end else begin
        mergeKopadLenStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mergeKopadStrm_din = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm_din;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mergeKopadStrm_din = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm_din;
    end else begin
        mergeKopadStrm_din = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mergeKopadStrm_write = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_mergeKopadStrm_write;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mergeKopadStrm_write = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_mergeKopadStrm_write;
    end else begin
        mergeKopadStrm_write = 1'b0;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        msgHashStrm_blk_n = msgHashStrm_empty_n;
    end else begin
        msgHashStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        msgHashStrm_read = 1'b1;
    end else begin
        msgHashStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((eMsgHashStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((eMsgHashStrm_dout == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((eMsgHashStrm_empty_n == 1'b0) | ((eMsgHashStrm_dout == 1'd1) & (eMergeKopadLenStrm_full_n == 1'b0)) | ((eMsgHashStrm_dout == 1'd0) & (eMergeKopadLenStrm_full_n == 1'b0)) | ((eMsgHashStrm_dout == 1'd0) & (msgHashStrm_empty_n == 1'b0)) | ((eMsgHashStrm_dout == 1'd0) & (kopad2Strm_empty_n == 1'b0)) | ((eMsgHashStrm_dout == 1'd0) & (mergeKopadLenStrm_full_n == 1'b0)));
end

assign ap_ready = internal_ap_ready;

assign grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_220_2_fu_91_ap_start_reg;

assign grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start = grp_mergeKopad_32_64_256_32_64_Pipeline_VITIS_LOOP_226_3_fu_98_ap_start_reg;

assign mergeKopadLenStrm_din = 64'd96;

assign start_out = real_start;

endmodule //test_hmac_sha256_mergeKopad_32_64_256_32_64_s
