// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mergeKipadStrm_dout,
        mergeKipadStrm_empty_n,
        mergeKipadStrm_read,
        mergeKipadStrm_num_data_valid,
        mergeKipadStrm_fifo_cap,
        blk_strm_din,
        blk_strm_full_n,
        blk_strm_write,
        blk_strm_num_data_valid,
        blk_strm_fifo_cap,
        trunc_ln
);

parameter    ap_ST_fsm_pp0_stage0 = 16'd1;
parameter    ap_ST_fsm_pp0_stage1 = 16'd2;
parameter    ap_ST_fsm_pp0_stage2 = 16'd4;
parameter    ap_ST_fsm_pp0_stage3 = 16'd8;
parameter    ap_ST_fsm_pp0_stage4 = 16'd16;
parameter    ap_ST_fsm_pp0_stage5 = 16'd32;
parameter    ap_ST_fsm_pp0_stage6 = 16'd64;
parameter    ap_ST_fsm_pp0_stage7 = 16'd128;
parameter    ap_ST_fsm_pp0_stage8 = 16'd256;
parameter    ap_ST_fsm_pp0_stage9 = 16'd512;
parameter    ap_ST_fsm_pp0_stage10 = 16'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 16'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 16'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 16'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 16'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mergeKipadStrm_dout;
input   mergeKipadStrm_empty_n;
output   mergeKipadStrm_read;
input  [7:0] mergeKipadStrm_num_data_valid;
input  [7:0] mergeKipadStrm_fifo_cap;
output  [511:0] blk_strm_din;
input   blk_strm_full_n;
output   blk_strm_write;
input  [5:0] blk_strm_num_data_valid;
input  [5:0] blk_strm_fifo_cap;
input  [57:0] trunc_ln;

reg ap_idle;
reg mergeKipadStrm_read;
reg blk_strm_write;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_block_state18_pp0_stage1_iter1_grp16;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln101_fu_125_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage15;
reg   [0:0] icmp_ln101_reg_290;
reg    ap_block_state16_pp0_stage15_iter0_grp14;
reg    ap_block_pp0_stage15_subdone;
reg    mergeKipadStrm_blk_n;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp1;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp2;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp3;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_grp4;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_grp5;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_grp6;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_grp7;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_grp8;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_grp9;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_grp10;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_grp11;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_grp12;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14_grp13;
wire    ap_block_pp0_stage15_grp14;
wire    ap_block_pp0_stage0_grp15;
wire    ap_block_pp0_stage1_grp16;
reg    blk_strm_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage1_11001;
wire   [7:0] empty_fu_141_p1;
reg   [7:0] empty_reg_294;
reg    ap_block_state3_pp0_stage2_iter0_grp1;
reg    ap_block_pp0_stage2_11001_grp1;
wire   [7:0] grp_fu_87_p4;
reg   [7:0] p_3_reg_299;
wire   [7:0] grp_fu_97_p4;
reg   [7:0] p_1_reg_304;
wire   [7:0] grp_fu_107_p4;
reg   [7:0] p_2_reg_309;
wire   [7:0] empty_49_fu_145_p1;
reg   [7:0] empty_49_reg_314;
reg    ap_block_state4_pp0_stage3_iter0_grp2;
reg    ap_block_pp0_stage3_11001_grp2;
reg   [7:0] p_s_reg_319;
reg   [7:0] p_13_reg_324;
reg   [7:0] p_24_reg_329;
wire   [7:0] empty_50_fu_149_p1;
reg   [7:0] empty_50_reg_334;
reg    ap_block_state5_pp0_stage4_iter0_grp3;
reg    ap_block_pp0_stage4_11001_grp3;
reg   [7:0] p_25_reg_339;
reg   [7:0] p_17_reg_344;
reg   [7:0] p_26_reg_349;
wire   [7:0] empty_51_fu_153_p1;
reg   [7:0] empty_51_reg_354;
reg    ap_block_state6_pp0_stage5_iter0_grp4;
reg    ap_block_pp0_stage5_11001_grp4;
reg   [7:0] p_27_reg_359;
reg   [7:0] p_28_reg_364;
reg   [7:0] p_29_reg_369;
wire   [7:0] empty_52_fu_157_p1;
reg   [7:0] empty_52_reg_374;
reg    ap_block_state7_pp0_stage6_iter0_grp5;
reg    ap_block_pp0_stage6_11001_grp5;
reg   [7:0] p_30_reg_379;
reg   [7:0] p_31_reg_384;
reg   [7:0] p_32_reg_389;
wire   [7:0] empty_53_fu_161_p1;
reg   [7:0] empty_53_reg_394;
reg    ap_block_state8_pp0_stage7_iter0_grp6;
reg    ap_block_pp0_stage7_11001_grp6;
reg   [7:0] p_33_reg_399;
reg   [7:0] p_34_reg_404;
reg   [7:0] p_35_reg_409;
wire   [7:0] empty_54_fu_165_p1;
reg   [7:0] empty_54_reg_414;
reg    ap_block_state9_pp0_stage8_iter0_grp7;
reg    ap_block_pp0_stage8_11001_grp7;
reg   [7:0] p_36_reg_419;
reg   [7:0] p_37_reg_424;
reg   [7:0] p_38_reg_429;
wire   [7:0] empty_55_fu_169_p1;
reg   [7:0] empty_55_reg_434;
reg    ap_block_state10_pp0_stage9_iter0_grp8;
reg    ap_block_pp0_stage9_11001_grp8;
reg   [7:0] p_39_reg_439;
reg   [7:0] p_40_reg_444;
reg   [7:0] p_41_reg_449;
wire   [7:0] empty_56_fu_173_p1;
reg   [7:0] empty_56_reg_454;
reg    ap_block_state11_pp0_stage10_iter0_grp9;
reg    ap_block_pp0_stage10_11001_grp9;
reg   [7:0] p_42_reg_459;
reg   [7:0] p_43_reg_464;
reg   [7:0] p_44_reg_469;
wire   [7:0] empty_57_fu_177_p1;
reg   [7:0] empty_57_reg_474;
reg    ap_block_state12_pp0_stage11_iter0_grp10;
reg    ap_block_pp0_stage11_11001_grp10;
reg   [7:0] p_45_reg_479;
reg   [7:0] p_46_reg_484;
reg   [7:0] p_47_reg_489;
wire   [7:0] empty_58_fu_181_p1;
reg   [7:0] empty_58_reg_494;
reg    ap_block_state13_pp0_stage12_iter0_grp11;
reg    ap_block_pp0_stage12_11001_grp11;
reg   [7:0] p_48_reg_499;
reg   [7:0] p_49_reg_504;
reg   [7:0] p_50_reg_509;
wire   [7:0] empty_59_fu_185_p1;
reg   [7:0] empty_59_reg_514;
reg    ap_block_state14_pp0_stage13_iter0_grp12;
reg    ap_block_pp0_stage13_11001_grp12;
reg   [7:0] p_51_reg_519;
reg   [7:0] p_52_reg_524;
reg   [7:0] p_53_reg_529;
wire   [7:0] empty_60_fu_189_p1;
reg   [7:0] empty_60_reg_534;
reg    ap_block_state15_pp0_stage14_iter0_grp13;
reg    ap_block_pp0_stage14_11001_grp13;
reg   [7:0] p_54_reg_539;
reg   [7:0] p_55_reg_544;
reg   [7:0] p_56_reg_549;
wire   [7:0] empty_61_fu_193_p1;
reg   [7:0] empty_61_reg_554;
reg    ap_block_pp0_stage15_11001_grp14;
reg   [7:0] p_57_reg_559;
reg   [7:0] p_58_reg_564;
reg   [7:0] p_59_reg_569;
wire   [7:0] empty_62_fu_197_p1;
reg   [7:0] empty_62_reg_574;
reg    ap_block_state17_pp0_stage0_iter1_grp15;
reg    ap_block_pp0_stage0_11001_grp15;
reg   [7:0] p_60_reg_579;
reg   [7:0] p_61_reg_584;
reg   [7:0] p_62_reg_589;
reg   [57:0] j_fu_64;
wire   [57:0] j_2_fu_130_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg    ap_block_pp0_stage1_11001_grp16;
reg    ap_block_pp0_stage1_01001_grp16;
wire   [7:0] empty_63_fu_201_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [15:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_block_pp0_stage7_subdone;
reg    ap_block_pp0_stage8_subdone;
reg    ap_block_pp0_stage9_subdone;
reg    ap_block_pp0_stage10_subdone;
reg    ap_block_pp0_stage11_subdone;
reg    ap_block_pp0_stage12_subdone;
reg    ap_block_pp0_stage13_subdone;
reg    ap_block_pp0_stage14_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 j_fu_64 = 58'd0;
#0 ap_done_reg = 1'b0;
end

test_hmac_sha256_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_64 <= 58'd0;
    end else if (((icmp_ln101_fu_125_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        j_fu_64 <= j_2_fu_130_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_49_reg_314 <= empty_49_fu_145_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        empty_50_reg_334 <= empty_50_fu_149_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        empty_51_reg_354 <= empty_51_fu_153_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        empty_52_reg_374 <= empty_52_fu_157_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        empty_53_reg_394 <= empty_53_fu_161_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        empty_54_reg_414 <= empty_54_fu_165_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        empty_55_reg_434 <= empty_55_fu_169_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        empty_56_reg_454 <= empty_56_fu_173_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        empty_57_reg_474 <= empty_57_fu_177_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        empty_58_reg_494 <= empty_58_fu_181_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage13_11001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        empty_59_reg_514 <= empty_59_fu_185_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage14_11001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        empty_60_reg_534 <= empty_60_fu_189_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage15_11001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        empty_61_reg_554 <= empty_61_fu_193_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp15) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_62_reg_574 <= empty_62_fu_197_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_reg_294 <= empty_fu_141_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        icmp_ln101_reg_290 <= icmp_ln101_fu_125_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_13_reg_324 <= {{mergeKipadStrm_dout[15:8]}};
        p_24_reg_329 <= {{mergeKipadStrm_dout[23:16]}};
        p_s_reg_319 <= {{mergeKipadStrm_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        p_17_reg_344 <= {{mergeKipadStrm_dout[15:8]}};
        p_25_reg_339 <= {{mergeKipadStrm_dout[31:24]}};
        p_26_reg_349 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_1_reg_304 <= {{mergeKipadStrm_dout[15:8]}};
        p_2_reg_309 <= {{mergeKipadStrm_dout[23:16]}};
        p_3_reg_299 <= {{mergeKipadStrm_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        p_27_reg_359 <= {{mergeKipadStrm_dout[31:24]}};
        p_28_reg_364 <= {{mergeKipadStrm_dout[15:8]}};
        p_29_reg_369 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        p_30_reg_379 <= {{mergeKipadStrm_dout[31:24]}};
        p_31_reg_384 <= {{mergeKipadStrm_dout[15:8]}};
        p_32_reg_389 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        p_33_reg_399 <= {{mergeKipadStrm_dout[31:24]}};
        p_34_reg_404 <= {{mergeKipadStrm_dout[15:8]}};
        p_35_reg_409 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        p_36_reg_419 <= {{mergeKipadStrm_dout[31:24]}};
        p_37_reg_424 <= {{mergeKipadStrm_dout[15:8]}};
        p_38_reg_429 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        p_39_reg_439 <= {{mergeKipadStrm_dout[31:24]}};
        p_40_reg_444 <= {{mergeKipadStrm_dout[15:8]}};
        p_41_reg_449 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        p_42_reg_459 <= {{mergeKipadStrm_dout[31:24]}};
        p_43_reg_464 <= {{mergeKipadStrm_dout[15:8]}};
        p_44_reg_469 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        p_45_reg_479 <= {{mergeKipadStrm_dout[31:24]}};
        p_46_reg_484 <= {{mergeKipadStrm_dout[15:8]}};
        p_47_reg_489 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        p_48_reg_499 <= {{mergeKipadStrm_dout[31:24]}};
        p_49_reg_504 <= {{mergeKipadStrm_dout[15:8]}};
        p_50_reg_509 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        p_51_reg_519 <= {{mergeKipadStrm_dout[31:24]}};
        p_52_reg_524 <= {{mergeKipadStrm_dout[15:8]}};
        p_53_reg_529 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        p_54_reg_539 <= {{mergeKipadStrm_dout[31:24]}};
        p_55_reg_544 <= {{mergeKipadStrm_dout[15:8]}};
        p_56_reg_549 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        p_57_reg_559 <= {{mergeKipadStrm_dout[31:24]}};
        p_58_reg_564 <= {{mergeKipadStrm_dout[15:8]}};
        p_59_reg_569 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_60_reg_579 <= {{mergeKipadStrm_dout[31:24]}};
        p_61_reg_584 <= {{mergeKipadStrm_dout[15:8]}};
        p_62_reg_589 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (*) begin
    if (((icmp_ln101_fu_125_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        blk_strm_blk_n = blk_strm_full_n;
    end else begin
        blk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        blk_strm_write = 1'b1;
    end else begin
        blk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_grp8) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((icmp_ln101_reg_290 
    == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln101_reg_290 == 1'd0) & (1'b0 == ap_block_pp0_stage0_grp15) 
    & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        mergeKipadStrm_blk_n = mergeKipadStrm_empty_n;
    end else begin
        mergeKipadStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001_grp14) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001_grp13) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001_grp12) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001_grp11) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001_grp10) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001_grp9) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001_grp8) 
    & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001_grp7) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001_grp6) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001_grp5) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001_grp4) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp3) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln101_reg_290 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) 
    & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln101_reg_290 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001_grp16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        mergeKipadStrm_read = 1'b1;
    end else begin
        mergeKipadStrm_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp15 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter1_grp15));
end

assign ap_block_pp0_stage0_grp15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state17_pp0_stage0_iter1_grp15));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_11001_grp9 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state11_pp0_stage10_iter0_grp9));
end

assign ap_block_pp0_stage10_grp9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage10_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state11_pp0_stage10_iter0_grp9));
end

always @ (*) begin
    ap_block_pp0_stage11_11001_grp10 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp10));
end

assign ap_block_pp0_stage11_grp10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage11_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state12_pp0_stage11_iter0_grp10));
end

always @ (*) begin
    ap_block_pp0_stage12_11001_grp11 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state13_pp0_stage12_iter0_grp11));
end

assign ap_block_pp0_stage12_grp11 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage12_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state13_pp0_stage12_iter0_grp11));
end

always @ (*) begin
    ap_block_pp0_stage13_11001_grp12 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state14_pp0_stage13_iter0_grp12));
end

assign ap_block_pp0_stage13_grp12 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage13_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state14_pp0_stage13_iter0_grp12));
end

always @ (*) begin
    ap_block_pp0_stage14_11001_grp13 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state15_pp0_stage14_iter0_grp13));
end

assign ap_block_pp0_stage14_grp13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage14_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state15_pp0_stage14_iter0_grp13));
end

always @ (*) begin
    ap_block_pp0_stage15_11001_grp14 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state16_pp0_stage15_iter0_grp14));
end

assign ap_block_pp0_stage15_grp14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage15_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state16_pp0_stage15_iter0_grp14));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp16 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

assign ap_block_pp0_stage1_grp16 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state18_pp0_stage1_iter1_grp16));
end

always @ (*) begin
    ap_block_pp0_stage2_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

assign ap_block_pp0_stage2_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp2 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp2));
end

assign ap_block_pp0_stage3_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state4_pp0_stage3_iter0_grp2));
end

always @ (*) begin
    ap_block_pp0_stage4_11001_grp3 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp3));
end

assign ap_block_pp0_stage4_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_pp0_stage4_iter0_grp3));
end

always @ (*) begin
    ap_block_pp0_stage5_11001_grp4 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp4));
end

assign ap_block_pp0_stage5_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state6_pp0_stage5_iter0_grp4));
end

always @ (*) begin
    ap_block_pp0_stage6_11001_grp5 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp5));
end

assign ap_block_pp0_stage6_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state7_pp0_stage6_iter0_grp5));
end

always @ (*) begin
    ap_block_pp0_stage7_11001_grp6 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp6));
end

assign ap_block_pp0_stage7_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state8_pp0_stage7_iter0_grp6));
end

always @ (*) begin
    ap_block_pp0_stage8_11001_grp7 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state9_pp0_stage8_iter0_grp7));
end

assign ap_block_pp0_stage8_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage8_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state9_pp0_stage8_iter0_grp7));
end

always @ (*) begin
    ap_block_pp0_stage9_11001_grp8 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0_grp8));
end

assign ap_block_pp0_stage9_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage9_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state10_pp0_stage9_iter0_grp8));
end

always @ (*) begin
    ap_block_state10_pp0_stage9_iter0_grp8 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state11_pp0_stage10_iter0_grp9 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state12_pp0_stage11_iter0_grp10 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp0_stage12_iter0_grp11 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state14_pp0_stage13_iter0_grp12 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state15_pp0_stage14_iter0_grp13 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state16_pp0_stage15_iter0_grp14 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state17_pp0_stage0_iter1_grp15 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state18_pp0_stage1_iter1_grp16 = ((blk_strm_full_n == 1'b0) | (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp1 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp2 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp3 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0_grp4 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0_grp5 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0_grp6 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp0_stage8_iter0_grp7 = ((icmp_ln101_reg_290 == 1'd0) & (mergeKipadStrm_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign blk_strm_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{empty_63_fu_201_p1}, {grp_fu_97_p4}}, {grp_fu_107_p4}}, {grp_fu_87_p4}}, {empty_62_reg_574}}, {p_61_reg_584}}, {p_62_reg_589}}, {p_60_reg_579}}, {empty_61_reg_554}}, {p_58_reg_564}}, {p_59_reg_569}}, {p_57_reg_559}}, {empty_60_reg_534}}, {p_55_reg_544}}, {p_56_reg_549}}, {p_54_reg_539}}, {empty_59_reg_514}}, {p_52_reg_524}}, {p_53_reg_529}}, {p_51_reg_519}}, {empty_58_reg_494}}, {p_49_reg_504}}, {p_50_reg_509}}, {p_48_reg_499}}, {empty_57_reg_474}}, {p_46_reg_484}}, {p_47_reg_489}}, {p_45_reg_479}}, {empty_56_reg_454}}, {p_43_reg_464}}, {p_44_reg_469}}, {p_42_reg_459}}, {empty_55_reg_434}}, {p_40_reg_444}}, {p_41_reg_449}}, {p_39_reg_439}}, {empty_54_reg_414}}, {p_37_reg_424}}, {p_38_reg_429}}, {p_36_reg_419}}, {empty_53_reg_394}}, {p_34_reg_404}}, {p_35_reg_409}}, {p_33_reg_399}}, {empty_52_reg_374}}, {p_31_reg_384}}, {p_32_reg_389}}, {p_30_reg_379}}, {empty_51_reg_354}}, {p_28_reg_364}}, {p_29_reg_369}}, {p_27_reg_359}}, {empty_50_reg_334}}, {p_17_reg_344}}, 
    {p_26_reg_349}}, {p_25_reg_339}}, {empty_49_reg_314}}, {p_13_reg_324}}, {p_24_reg_329}}, {p_s_reg_319}}, {empty_reg_294}}, {p_1_reg_304}}, {p_2_reg_309}}, {p_3_reg_299}};

assign empty_49_fu_145_p1 = mergeKipadStrm_dout[7:0];

assign empty_50_fu_149_p1 = mergeKipadStrm_dout[7:0];

assign empty_51_fu_153_p1 = mergeKipadStrm_dout[7:0];

assign empty_52_fu_157_p1 = mergeKipadStrm_dout[7:0];

assign empty_53_fu_161_p1 = mergeKipadStrm_dout[7:0];

assign empty_54_fu_165_p1 = mergeKipadStrm_dout[7:0];

assign empty_55_fu_169_p1 = mergeKipadStrm_dout[7:0];

assign empty_56_fu_173_p1 = mergeKipadStrm_dout[7:0];

assign empty_57_fu_177_p1 = mergeKipadStrm_dout[7:0];

assign empty_58_fu_181_p1 = mergeKipadStrm_dout[7:0];

assign empty_59_fu_185_p1 = mergeKipadStrm_dout[7:0];

assign empty_60_fu_189_p1 = mergeKipadStrm_dout[7:0];

assign empty_61_fu_193_p1 = mergeKipadStrm_dout[7:0];

assign empty_62_fu_197_p1 = mergeKipadStrm_dout[7:0];

assign empty_63_fu_201_p1 = mergeKipadStrm_dout[7:0];

assign empty_fu_141_p1 = mergeKipadStrm_dout[7:0];

assign grp_fu_107_p4 = {{mergeKipadStrm_dout[23:16]}};

assign grp_fu_87_p4 = {{mergeKipadStrm_dout[31:24]}};

assign grp_fu_97_p4 = {{mergeKipadStrm_dout[15:8]}};

assign icmp_ln101_fu_125_p2 = ((j_fu_64 == trunc_ln) ? 1'b1 : 1'b0);

assign j_2_fu_130_p2 = (j_fu_64 + 58'd1);

endmodule //test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS
