// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_hash (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        mergeKipadStrm_dout,
        mergeKipadStrm_empty_n,
        mergeKipadStrm_read,
        mergeKipadStrm_num_data_valid,
        mergeKipadStrm_fifo_cap,
        mergeKipadLenStrm_dout,
        mergeKipadLenStrm_empty_n,
        mergeKipadLenStrm_read,
        mergeKipadLenStrm_num_data_valid,
        mergeKipadLenStrm_fifo_cap,
        eMergeKipadLenStrm_dout,
        eMergeKipadLenStrm_empty_n,
        eMergeKipadLenStrm_read,
        eMergeKipadLenStrm_num_data_valid,
        eMergeKipadLenStrm_fifo_cap,
        msgHashStrm_din,
        msgHashStrm_full_n,
        msgHashStrm_write,
        msgHashStrm_num_data_valid,
        msgHashStrm_fifo_cap,
        eMsgHashStrm_din,
        eMsgHashStrm_full_n,
        eMsgHashStrm_write,
        eMsgHashStrm_num_data_valid,
        eMsgHashStrm_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] mergeKipadStrm_dout;
input   mergeKipadStrm_empty_n;
output   mergeKipadStrm_read;
input  [7:0] mergeKipadStrm_num_data_valid;
input  [7:0] mergeKipadStrm_fifo_cap;
input  [63:0] mergeKipadLenStrm_dout;
input   mergeKipadLenStrm_empty_n;
output   mergeKipadLenStrm_read;
input  [2:0] mergeKipadLenStrm_num_data_valid;
input  [2:0] mergeKipadLenStrm_fifo_cap;
input  [0:0] eMergeKipadLenStrm_dout;
input   eMergeKipadLenStrm_empty_n;
output   eMergeKipadLenStrm_read;
input  [2:0] eMergeKipadLenStrm_num_data_valid;
input  [2:0] eMergeKipadLenStrm_fifo_cap;
output  [255:0] msgHashStrm_din;
input   msgHashStrm_full_n;
output   msgHashStrm_write;
input  [2:0] msgHashStrm_num_data_valid;
input  [2:0] msgHashStrm_fifo_cap;
output  [0:0] eMsgHashStrm_din;
input   eMsgHashStrm_full_n;
output   eMsgHashStrm_write;
input  [2:0] eMsgHashStrm_num_data_valid;
input  [2:0] eMsgHashStrm_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_sha256_top_32_256_s_fu_32_mergeKopadStrm_read;
wire    grp_sha256_top_32_256_s_fu_32_mergeKopadLenStrm_read;
wire    grp_sha256_top_32_256_s_fu_32_eMergeKopadLenStrm_read;
wire   [255:0] grp_sha256_top_32_256_s_fu_32_hshStrm_din;
wire    grp_sha256_top_32_256_s_fu_32_hshStrm_write;
wire   [0:0] grp_sha256_top_32_256_s_fu_32_eHshStrm_din;
wire    grp_sha256_top_32_256_s_fu_32_eHshStrm_write;
wire    grp_sha256_top_32_256_s_fu_32_ap_start;
wire    grp_sha256_top_32_256_s_fu_32_ap_done;
wire    grp_sha256_top_32_256_s_fu_32_ap_ready;
wire    grp_sha256_top_32_256_s_fu_32_ap_idle;
reg    grp_sha256_top_32_256_s_fu_32_ap_continue;
reg    grp_sha256_top_32_256_s_fu_32_ap_start_reg;
reg    ap_block_state1_ignore_call10;
wire    ap_CS_fsm_state2;
reg    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready;
reg    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done;
reg    ap_block_state2_on_subcall_done;
wire    ap_sync_grp_sha256_top_32_256_s_fu_32_ap_ready;
reg   [1:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_sha256_top_32_256_s_fu_32_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready = 1'b0;
#0 ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done = 1'b0;
end

test_hmac_sha256_sha256_top_32_256_s grp_sha256_top_32_256_s_fu_32(
    .mergeKopadStrm_dout(mergeKipadStrm_dout),
    .mergeKopadStrm_empty_n(mergeKipadStrm_empty_n),
    .mergeKopadStrm_read(grp_sha256_top_32_256_s_fu_32_mergeKopadStrm_read),
    .mergeKopadLenStrm_dout(mergeKipadLenStrm_dout),
    .mergeKopadLenStrm_empty_n(mergeKipadLenStrm_empty_n),
    .mergeKopadLenStrm_read(grp_sha256_top_32_256_s_fu_32_mergeKopadLenStrm_read),
    .eMergeKopadLenStrm_dout(eMergeKipadLenStrm_dout),
    .eMergeKopadLenStrm_empty_n(eMergeKipadLenStrm_empty_n),
    .eMergeKopadLenStrm_read(grp_sha256_top_32_256_s_fu_32_eMergeKopadLenStrm_read),
    .hshStrm_din(grp_sha256_top_32_256_s_fu_32_hshStrm_din),
    .hshStrm_full_n(msgHashStrm_full_n),
    .hshStrm_write(grp_sha256_top_32_256_s_fu_32_hshStrm_write),
    .eHshStrm_din(grp_sha256_top_32_256_s_fu_32_eHshStrm_din),
    .eHshStrm_full_n(eMsgHashStrm_full_n),
    .eHshStrm_write(grp_sha256_top_32_256_s_fu_32_eHshStrm_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_top_32_256_s_fu_32_ap_start),
    .ap_done(grp_sha256_top_32_256_s_fu_32_ap_done),
    .ap_ready(grp_sha256_top_32_256_s_fu_32_ap_ready),
    .ap_idle(grp_sha256_top_32_256_s_fu_32_ap_idle),
    .ap_continue(grp_sha256_top_32_256_s_fu_32_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done <= 1'b0;
        end else if ((grp_sha256_top_32_256_s_fu_32_ap_done == 1'b1)) begin
            ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready <= 1'b0;
        end else if ((grp_sha256_top_32_256_s_fu_32_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_top_32_256_s_fu_32_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_state1_ignore_call10) & (1'b1 == ap_CS_fsm_state1)) | ((ap_sync_grp_sha256_top_32_256_s_fu_32_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state2)))) begin
            grp_sha256_top_32_256_s_fu_32_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_top_32_256_s_fu_32_ap_ready == 1'b1)) begin
            grp_sha256_top_32_256_s_fu_32_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_sha256_top_32_256_s_fu_32_ap_continue = 1'b1;
    end else begin
        grp_sha256_top_32_256_s_fu_32_ap_continue = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call10 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready & ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done) == 1'b0);
end

assign ap_sync_grp_sha256_top_32_256_s_fu_32_ap_ready = (grp_sha256_top_32_256_s_fu_32_ap_ready | ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready);

assign eMergeKipadLenStrm_read = grp_sha256_top_32_256_s_fu_32_eMergeKopadLenStrm_read;

assign eMsgHashStrm_din = grp_sha256_top_32_256_s_fu_32_eHshStrm_din;

assign eMsgHashStrm_write = grp_sha256_top_32_256_s_fu_32_eHshStrm_write;

assign grp_sha256_top_32_256_s_fu_32_ap_start = grp_sha256_top_32_256_s_fu_32_ap_start_reg;

assign mergeKipadLenStrm_read = grp_sha256_top_32_256_s_fu_32_mergeKopadLenStrm_read;

assign mergeKipadStrm_read = grp_sha256_top_32_256_s_fu_32_mergeKopadStrm_read;

assign msgHashStrm_din = grp_sha256_top_32_256_s_fu_32_hshStrm_din;

assign msgHashStrm_write = grp_sha256_top_32_256_s_fu_32_hshStrm_write;

endmodule //test_hmac_sha256_hash
