// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_preProcessing (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        mergeKipadStrm_dout,
        mergeKipadStrm_empty_n,
        mergeKipadStrm_read,
        mergeKipadStrm_num_data_valid,
        mergeKipadStrm_fifo_cap,
        mergeKipadLenStrm_dout,
        mergeKipadLenStrm_empty_n,
        mergeKipadLenStrm_read,
        mergeKipadLenStrm_num_data_valid,
        mergeKipadLenStrm_fifo_cap,
        eMergeKipadLenStrm_dout,
        eMergeKipadLenStrm_empty_n,
        eMergeKipadLenStrm_read,
        eMergeKipadLenStrm_num_data_valid,
        eMergeKipadLenStrm_fifo_cap,
        blk_strm_din,
        blk_strm_full_n,
        blk_strm_write,
        blk_strm_num_data_valid,
        blk_strm_fifo_cap,
        nblk_strm_din,
        nblk_strm_full_n,
        nblk_strm_write,
        nblk_strm_num_data_valid,
        nblk_strm_fifo_cap,
        end_nblk_strm_din,
        end_nblk_strm_full_n,
        end_nblk_strm_write,
        end_nblk_strm_num_data_valid,
        end_nblk_strm_fifo_cap
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] mergeKipadStrm_dout;
input   mergeKipadStrm_empty_n;
output   mergeKipadStrm_read;
input  [7:0] mergeKipadStrm_num_data_valid;
input  [7:0] mergeKipadStrm_fifo_cap;
input  [63:0] mergeKipadLenStrm_dout;
input   mergeKipadLenStrm_empty_n;
output   mergeKipadLenStrm_read;
input  [2:0] mergeKipadLenStrm_num_data_valid;
input  [2:0] mergeKipadLenStrm_fifo_cap;
input  [0:0] eMergeKipadLenStrm_dout;
input   eMergeKipadLenStrm_empty_n;
output   eMergeKipadLenStrm_read;
input  [2:0] eMergeKipadLenStrm_num_data_valid;
input  [2:0] eMergeKipadLenStrm_fifo_cap;
output  [511:0] blk_strm_din;
input   blk_strm_full_n;
output   blk_strm_write;
input  [5:0] blk_strm_num_data_valid;
input  [5:0] blk_strm_fifo_cap;
output  [63:0] nblk_strm_din;
input   nblk_strm_full_n;
output   nblk_strm_write;
input  [5:0] nblk_strm_num_data_valid;
input  [5:0] nblk_strm_fifo_cap;
output  [0:0] end_nblk_strm_din;
input   end_nblk_strm_full_n;
output   end_nblk_strm_write;
input  [5:0] end_nblk_strm_num_data_valid;
input  [5:0] end_nblk_strm_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg mergeKipadStrm_read;
reg mergeKipadLenStrm_read;
reg eMergeKipadLenStrm_read;
reg[511:0] blk_strm_din;
reg blk_strm_write;
reg nblk_strm_write;
reg[0:0] end_nblk_strm_din;
reg end_nblk_strm_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    mergeKipadStrm_blk_n;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln129_fu_422_p2;
wire   [0:0] icmp_ln152_fu_427_p2;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln215_fu_543_p2;
wire   [0:0] cmp275_fu_528_p2;
wire    ap_CS_fsm_state21;
wire   [0:0] or_ln223_fu_611_p2;
reg    mergeKipadLenStrm_blk_n;
wire    ap_CS_fsm_state2;
reg    eMergeKipadLenStrm_blk_n;
wire    ap_CS_fsm_state23;
reg    blk_strm_blk_n;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state22;
reg   [0:0] icmp_ln129_reg_957;
reg   [0:0] icmp_ln152_reg_961;
reg    nblk_strm_blk_n;
wire    ap_CS_fsm_state3;
reg    end_nblk_strm_blk_n;
reg    ap_block_state1;
reg   [63:0] len_reg_919;
reg    ap_block_state2;
wire   [1:0] trunc_ln91_fu_341_p1;
reg   [1:0] trunc_ln91_reg_925;
wire   [5:0] left_fu_345_p1;
reg   [5:0] left_reg_933;
wire   [28:0] trunc_ln264_fu_349_p1;
reg   [28:0] trunc_ln264_reg_939;
reg   [57:0] trunc_ln_reg_946;
wire   [0:0] icmp_ln95_fu_363_p2;
reg   [0:0] icmp_ln95_reg_952;
reg    ap_predicate_op80_read_state6;
reg    ap_block_state6;
reg   [3:0] p_cast_reg_965;
wire   [7:0] empty_fu_442_p1;
reg   [7:0] empty_reg_972;
wire   [7:0] grp_fu_302_p4;
reg   [7:0] p_s_reg_977;
wire   [7:0] grp_fu_312_p4;
reg   [7:0] p_68_reg_982;
wire   [7:0] grp_fu_322_p4;
reg   [7:0] p_69_reg_987;
wire   [7:0] empty_64_fu_476_p1;
reg   [7:0] empty_64_reg_992;
reg   [7:0] p_70_reg_997;
reg   [7:0] p_71_reg_1002;
reg   [7:0] p_72_reg_1007;
wire   [7:0] empty_65_fu_480_p1;
reg   [7:0] empty_65_reg_1012;
reg   [7:0] p_73_reg_1017;
reg   [7:0] p_74_reg_1022;
reg   [7:0] p_75_reg_1027;
wire   [7:0] empty_66_fu_484_p1;
reg   [7:0] empty_66_reg_1032;
reg   [7:0] p_76_reg_1037;
reg   [7:0] p_77_reg_1042;
reg   [7:0] p_78_reg_1047;
wire   [7:0] empty_67_fu_488_p1;
reg   [7:0] empty_67_reg_1052;
reg   [7:0] p_79_reg_1057;
reg   [7:0] p_80_reg_1062;
reg   [7:0] p_81_reg_1067;
wire   [7:0] empty_68_fu_492_p1;
reg   [7:0] empty_68_reg_1072;
reg   [7:0] p_82_reg_1077;
reg   [7:0] p_83_reg_1082;
reg   [7:0] p_84_reg_1087;
wire   [7:0] empty_69_fu_496_p1;
reg   [7:0] empty_69_reg_1092;
reg   [7:0] p_85_reg_1097;
reg   [7:0] p_86_reg_1102;
reg   [7:0] p_87_reg_1107;
wire   [7:0] empty_70_fu_500_p1;
reg   [7:0] empty_70_reg_1112;
reg   [7:0] p_88_reg_1117;
reg   [7:0] p_89_reg_1122;
reg   [7:0] p_90_reg_1127;
wire   [7:0] empty_71_fu_504_p1;
reg   [7:0] empty_71_reg_1132;
reg   [7:0] p_91_reg_1137;
reg   [7:0] p_92_reg_1142;
reg   [7:0] p_93_reg_1147;
wire   [7:0] empty_72_fu_508_p1;
reg   [7:0] empty_72_reg_1152;
reg   [7:0] p_94_reg_1157;
reg   [7:0] p_95_reg_1162;
reg   [7:0] p_96_reg_1167;
wire   [7:0] empty_73_fu_512_p1;
reg   [7:0] empty_73_reg_1172;
reg   [7:0] p_97_reg_1177;
reg   [7:0] p_98_reg_1182;
reg   [7:0] p_99_reg_1187;
wire   [7:0] empty_74_fu_516_p1;
reg   [7:0] empty_74_reg_1192;
reg   [7:0] p_100_reg_1197;
reg   [7:0] p_101_reg_1202;
reg   [7:0] p_102_reg_1207;
wire   [7:0] empty_75_fu_520_p1;
reg   [7:0] empty_75_reg_1212;
reg   [7:0] p_103_reg_1217;
reg   [7:0] p_104_reg_1222;
reg   [7:0] p_105_reg_1227;
wire   [7:0] empty_76_fu_524_p1;
reg   [7:0] empty_76_reg_1232;
reg   [7:0] p_106_reg_1237;
reg   [7:0] p_107_reg_1242;
reg   [7:0] p_108_reg_1247;
reg   [0:0] cmp275_reg_1252;
reg    ap_predicate_op162_read_state20;
reg    ap_block_state20;
wire   [0:0] cmp281_fu_533_p2;
reg   [0:0] cmp281_reg_1257;
wire   [0:0] cmp298_fu_538_p2;
reg   [0:0] cmp298_reg_1261;
wire   [31:0] or_ln4_fu_552_p5;
wire   [31:0] or_ln3_fu_568_p4;
wire   [31:0] or_ln_fu_582_p3;
wire   [31:0] l_43_fu_594_p5;
wire   [0:0] icmp_ln223_fu_606_p2;
reg   [0:0] icmp_ln223_reg_1288;
wire   [31:0] select_ln223_fu_615_p3;
reg    ap_block_state21;
wire   [31:0] or_ln245_2_fu_626_p5;
wire   [31:0] or_ln240_1_fu_642_p4;
wire   [31:0] or_ln235_1_fu_656_p3;
wire   [31:0] grp_fu_332_p4;
reg   [31:0] tmp_7_reg_1317;
reg    ap_predicate_op207_write_state23;
reg    ap_block_state23;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_done;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_idle;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_ready;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_mergeKipadStrm_read;
wire   [511:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_blk_strm_din;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_blk_strm_write;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_done;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_idle;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_ready;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_mergeKipadStrm_read;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_16_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_16_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_15_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_15_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_14_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_14_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_13_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_13_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_12_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_12_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_11_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_11_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_10_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_10_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_9_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_9_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_8_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_8_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_7_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_7_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_6_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_6_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_5_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_5_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_4_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_4_out_ap_vld;
wire   [31:0] grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_out;
wire    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_out_ap_vld;
reg   [0:0] end_flag_1_reg_231;
reg   [31:0] b225_0_14_load_reg_240;
reg   [31:0] storemerge93_reg_258;
reg    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start_reg;
reg   [24:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start_reg;
reg    ap_block_state6_ignore_call1;
wire    ap_CS_fsm_state24;
reg    ap_block_state3;
wire   [511:0] or_ln151_1_fu_464_p5;
wire   [511:0] or_ln250_s_fu_664_p59;
wire   [511:0] or_ln268_s_fu_729_p5;
wire   [511:0] or_ln203_s_fu_792_p18;
wire   [58:0] select_ln95_fu_372_p3;
wire   [58:0] zext_ln95_1_fu_369_p1;
wire   [58:0] blk_num_fu_379_p2;
wire   [7:0] trunc_ln245_fu_548_p1;
wire   [7:0] trunc_ln240_fu_564_p1;
wire   [7:0] trunc_ln234_fu_578_p1;
wire   [7:0] empty_77_fu_590_p1;
wire   [7:0] trunc_ln245_1_fu_622_p1;
wire   [7:0] trunc_ln240_1_fu_638_p1;
wire   [7:0] trunc_ln234_1_fu_652_p1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
reg    ap_condition_508;
reg    ap_condition_513;
reg    ap_condition_516;
reg    ap_condition_530;
reg    ap_condition_534;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 25'd1;
#0 grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start_reg = 1'b0;
#0 grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start_reg = 1'b0;
end

test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start),
    .ap_done(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_done),
    .ap_idle(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_idle),
    .ap_ready(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_ready),
    .mergeKipadStrm_dout(mergeKipadStrm_dout),
    .mergeKipadStrm_empty_n(mergeKipadStrm_empty_n),
    .mergeKipadStrm_read(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_mergeKipadStrm_read),
    .mergeKipadStrm_num_data_valid(8'd0),
    .mergeKipadStrm_fifo_cap(8'd0),
    .blk_strm_din(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_blk_strm_din),
    .blk_strm_full_n(blk_strm_full_n),
    .blk_strm_write(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_blk_strm_write),
    .blk_strm_num_data_valid(6'd0),
    .blk_strm_fifo_cap(6'd0),
    .trunc_ln(trunc_ln_reg_946)
);

test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start),
    .ap_done(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_done),
    .ap_idle(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_idle),
    .ap_ready(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_ready),
    .mergeKipadStrm_dout(mergeKipadStrm_dout),
    .mergeKipadStrm_empty_n(mergeKipadStrm_empty_n),
    .mergeKipadStrm_read(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_mergeKipadStrm_read),
    .mergeKipadStrm_num_data_valid(8'd0),
    .mergeKipadStrm_fifo_cap(8'd0),
    .p_cast(p_cast_reg_965),
    .len(trunc_ln91_reg_925),
    .b_16_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_16_out),
    .b_16_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_16_out_ap_vld),
    .b_15_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_15_out),
    .b_15_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_15_out_ap_vld),
    .b_14_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_14_out),
    .b_14_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_14_out_ap_vld),
    .b_13_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_13_out),
    .b_13_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_13_out_ap_vld),
    .b_12_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_12_out),
    .b_12_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_12_out_ap_vld),
    .b_11_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_11_out),
    .b_11_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_11_out_ap_vld),
    .b_10_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_10_out),
    .b_10_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_10_out_ap_vld),
    .b_9_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_9_out),
    .b_9_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_9_out_ap_vld),
    .b_8_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_8_out),
    .b_8_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_8_out_ap_vld),
    .b_7_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_7_out),
    .b_7_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_7_out_ap_vld),
    .b_6_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_6_out),
    .b_6_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_6_out_ap_vld),
    .b_5_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_5_out),
    .b_5_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_5_out_ap_vld),
    .b_4_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_4_out),
    .b_4_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_4_out_ap_vld),
    .b_out(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_out),
    .b_out_ap_vld(grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state6_ignore_call1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln152_fu_427_p2 == 1'd1) & (icmp_ln129_fu_422_p2 == 1'd0))) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start_reg <= 1'b1;
        end else if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_ready == 1'b1)) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start_reg <= 1'b1;
        end else if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_ready == 1'b1)) begin
            grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state20) & (1'b1 == ap_CS_fsm_state20))) begin
        if (((cmp275_fu_528_p2 == 1'd1) & (icmp_ln215_fu_543_p2 == 1'd0))) begin
            b225_0_14_load_reg_240 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_516)) begin
            b225_0_14_load_reg_240 <= or_ln3_fu_568_p4;
        end else if ((1'b1 == ap_condition_513)) begin
            b225_0_14_load_reg_240 <= or_ln4_fu_552_p5;
        end else if ((1'b1 == ap_condition_508)) begin
            b225_0_14_load_reg_240 <= or_ln_fu_582_p3;
        end else if ((icmp_ln215_fu_543_p2 == 1'd1)) begin
            b225_0_14_load_reg_240 <= l_43_fu_594_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state21) & (1'b1 == ap_CS_fsm_state21))) begin
        if ((or_ln223_fu_611_p2 == 1'd1)) begin
                        storemerge93_reg_258[31 : 7] <= select_ln223_fu_615_p3[31 : 7];
        end else if ((1'b1 == ap_condition_534)) begin
                        storemerge93_reg_258[31 : 7] <= or_ln240_1_fu_642_p4[31 : 7];
        end else if ((1'b1 == ap_condition_530)) begin
                        storemerge93_reg_258[31 : 7] <= or_ln245_2_fu_626_p5[31 : 7];
        end else if (((cmp281_reg_1257 == 1'd1) & (or_ln223_fu_611_p2 == 1'd0))) begin
                        storemerge93_reg_258[31 : 7] <= or_ln235_1_fu_656_p3[31 : 7];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state20) & (1'b1 == ap_CS_fsm_state20))) begin
        cmp275_reg_1252 <= cmp275_fu_528_p2;
        cmp281_reg_1257 <= cmp281_fu_533_p2;
        cmp298_reg_1261 <= cmp298_fu_538_p2;
        icmp_ln223_reg_1288 <= icmp_ln223_fu_606_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        empty_64_reg_992 <= empty_64_fu_476_p1;
        p_70_reg_997 <= {{mergeKipadStrm_dout[31:24]}};
        p_71_reg_1002 <= {{mergeKipadStrm_dout[15:8]}};
        p_72_reg_1007 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        empty_65_reg_1012 <= empty_65_fu_480_p1;
        p_73_reg_1017 <= {{mergeKipadStrm_dout[31:24]}};
        p_74_reg_1022 <= {{mergeKipadStrm_dout[15:8]}};
        p_75_reg_1027 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        empty_66_reg_1032 <= empty_66_fu_484_p1;
        p_76_reg_1037 <= {{mergeKipadStrm_dout[31:24]}};
        p_77_reg_1042 <= {{mergeKipadStrm_dout[15:8]}};
        p_78_reg_1047 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        empty_67_reg_1052 <= empty_67_fu_488_p1;
        p_79_reg_1057 <= {{mergeKipadStrm_dout[31:24]}};
        p_80_reg_1062 <= {{mergeKipadStrm_dout[15:8]}};
        p_81_reg_1067 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        empty_68_reg_1072 <= empty_68_fu_492_p1;
        p_82_reg_1077 <= {{mergeKipadStrm_dout[31:24]}};
        p_83_reg_1082 <= {{mergeKipadStrm_dout[15:8]}};
        p_84_reg_1087 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        empty_69_reg_1092 <= empty_69_fu_496_p1;
        p_85_reg_1097 <= {{mergeKipadStrm_dout[31:24]}};
        p_86_reg_1102 <= {{mergeKipadStrm_dout[15:8]}};
        p_87_reg_1107 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        empty_70_reg_1112 <= empty_70_fu_500_p1;
        p_88_reg_1117 <= {{mergeKipadStrm_dout[31:24]}};
        p_89_reg_1122 <= {{mergeKipadStrm_dout[15:8]}};
        p_90_reg_1127 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        empty_71_reg_1132 <= empty_71_fu_504_p1;
        p_91_reg_1137 <= {{mergeKipadStrm_dout[31:24]}};
        p_92_reg_1142 <= {{mergeKipadStrm_dout[15:8]}};
        p_93_reg_1147 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        empty_72_reg_1152 <= empty_72_fu_508_p1;
        p_94_reg_1157 <= {{mergeKipadStrm_dout[31:24]}};
        p_95_reg_1162 <= {{mergeKipadStrm_dout[15:8]}};
        p_96_reg_1167 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        empty_73_reg_1172 <= empty_73_fu_512_p1;
        p_97_reg_1177 <= {{mergeKipadStrm_dout[31:24]}};
        p_98_reg_1182 <= {{mergeKipadStrm_dout[15:8]}};
        p_99_reg_1187 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        empty_74_reg_1192 <= empty_74_fu_516_p1;
        p_100_reg_1197 <= {{mergeKipadStrm_dout[31:24]}};
        p_101_reg_1202 <= {{mergeKipadStrm_dout[15:8]}};
        p_102_reg_1207 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        empty_75_reg_1212 <= empty_75_fu_520_p1;
        p_103_reg_1217 <= {{mergeKipadStrm_dout[31:24]}};
        p_104_reg_1222 <= {{mergeKipadStrm_dout[15:8]}};
        p_105_reg_1227 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        empty_76_reg_1232 <= empty_76_fu_524_p1;
        p_106_reg_1237 <= {{mergeKipadStrm_dout[31:24]}};
        p_107_reg_1242 <= {{mergeKipadStrm_dout[15:8]}};
        p_108_reg_1247 <= {{mergeKipadStrm_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        empty_reg_972 <= empty_fu_442_p1;
        icmp_ln129_reg_957 <= icmp_ln129_fu_422_p2;
        icmp_ln152_reg_961 <= icmp_ln152_fu_427_p2;
        p_68_reg_982 <= {{mergeKipadStrm_dout[15:8]}};
        p_69_reg_987 <= {{mergeKipadStrm_dout[23:16]}};
        p_cast_reg_965 <= {{len_reg_919[5:2]}};
        p_s_reg_977 <= {{mergeKipadStrm_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23)) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        end_flag_1_reg_231 <= eMergeKipadLenStrm_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln95_reg_952 <= icmp_ln95_fu_363_p2;
        left_reg_933 <= left_fu_345_p1;
        len_reg_919 <= mergeKipadLenStrm_dout;
        trunc_ln264_reg_939 <= trunc_ln264_fu_349_p1;
        trunc_ln91_reg_925 <= trunc_ln91_fu_341_p1;
        trunc_ln_reg_946 <= {{mergeKipadLenStrm_dout[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state21) & (1'b1 == ap_CS_fsm_state21))) begin
        tmp_7_reg_1317 <= {{len_reg_919[60:29]}};
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state20)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state21)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((blk_strm_full_n == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state23)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((blk_strm_full_n == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((mergeKipadStrm_empty_n == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state25) | ((icmp_ln152_reg_961 == 1'd0) & (icmp_ln129_reg_957 == 1'd0) & (1'b1 == ap_CS_fsm_state23)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln129_fu_422_p2 == 1'd1)))) begin
        blk_strm_blk_n = blk_strm_full_n;
    end else begin
        blk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((blk_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        blk_strm_din = or_ln203_s_fu_792_p18;
    end else if (((ap_predicate_op207_write_state23 == 1'b1) & (1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23))) begin
        blk_strm_din = or_ln268_s_fu_729_p5;
    end else if (((blk_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        blk_strm_din = or_ln250_s_fu_664_p59;
    end else if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln129_fu_422_p2 == 1'd1))) begin
        blk_strm_din = or_ln151_1_fu_464_p5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        blk_strm_din = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_blk_strm_din;
    end else begin
        blk_strm_din = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_blk_strm_din;
    end
end

always @ (*) begin
    if ((((blk_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((blk_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((ap_predicate_op207_write_state23 == 1'b1) & (1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23)) | ((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln129_fu_422_p2 == 1'd1)))) begin
        blk_strm_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        blk_strm_write = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_blk_strm_write;
    end else begin
        blk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        eMergeKipadLenStrm_blk_n = eMergeKipadLenStrm_empty_n;
    end else begin
        eMergeKipadLenStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23)) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        eMergeKipadLenStrm_read = 1'b1;
    end else begin
        eMergeKipadLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((end_flag_1_reg_231 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        end_nblk_strm_blk_n = end_nblk_strm_full_n;
    end else begin
        end_nblk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        end_nblk_strm_din = 1'd0;
    end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        end_nblk_strm_din = 1'd1;
    end else begin
        end_nblk_strm_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3)) | ((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        end_nblk_strm_write = 1'b1;
    end else begin
        end_nblk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((end_flag_1_reg_231 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mergeKipadLenStrm_blk_n = mergeKipadLenStrm_empty_n;
    end else begin
        mergeKipadLenStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        mergeKipadLenStrm_read = 1'b1;
    end else begin
        mergeKipadLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((or_ln223_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state20) & (icmp_ln215_fu_543_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state20) & (cmp275_fu_528_p2 == 1'd0) & (icmp_ln215_fu_543_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln152_fu_427_p2 == 1'd0) & (icmp_ln129_fu_422_p2 == 1'd0)))) begin
        mergeKipadStrm_blk_n = mergeKipadStrm_empty_n;
    end else begin
        mergeKipadStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state21) & (or_ln223_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21)) | ((1'b0 == ap_block_state20) & (1'b1 == ap_CS_fsm_state20) & (icmp_ln215_fu_543_p2 == 1'd1)) | ((ap_predicate_op162_read_state20 == 1'b1) & (1'b0 == ap_block_state20) & (1'b1 == ap_CS_fsm_state20)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) 
    | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((ap_predicate_op80_read_state6 == 1'b1) & (1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6)))) begin
        mergeKipadStrm_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        mergeKipadStrm_read = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_mergeKipadStrm_read;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mergeKipadStrm_read = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_mergeKipadStrm_read;
    end else begin
        mergeKipadStrm_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        nblk_strm_blk_n = nblk_strm_full_n;
    end else begin
        nblk_strm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
        nblk_strm_write = 1'b1;
    end else begin
        nblk_strm_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state2) & (end_flag_1_reg_231 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln129_fu_422_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln152_fu_427_p2 == 1'd1) & (icmp_ln129_fu_422_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln152_fu_427_p2 == 1'd0) & (icmp_ln129_fu_422_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((mergeKipadStrm_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b0 == ap_block_state20) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((1'b0 == ap_block_state21) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((blk_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((blk_strm_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((eMergeKipadLenStrm_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = (((end_nblk_strm_full_n == 1'b0) & (end_flag_1_reg_231 == 1'd1)) | ((mergeKipadLenStrm_empty_n == 1'b0) & (end_flag_1_reg_231 == 1'd0)));
end

always @ (*) begin
    ap_block_state20 = (((mergeKipadStrm_empty_n == 1'b0) & (ap_predicate_op162_read_state20 == 1'b1)) | ((mergeKipadStrm_empty_n == 1'b0) & (icmp_ln215_fu_543_p2 == 1'd1)));
end

always @ (*) begin
    ap_block_state21 = ((mergeKipadStrm_empty_n == 1'b0) & (or_ln223_fu_611_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state23 = ((eMergeKipadLenStrm_empty_n == 1'b0) | ((blk_strm_full_n == 1'b0) & (ap_predicate_op207_write_state23 == 1'b1)));
end

always @ (*) begin
    ap_block_state3 = ((end_nblk_strm_full_n == 1'b0) | (nblk_strm_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state6 = (((blk_strm_full_n == 1'b0) & (icmp_ln129_fu_422_p2 == 1'd1)) | ((mergeKipadStrm_empty_n == 1'b0) & (ap_predicate_op80_read_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_ignore_call1 = (((blk_strm_full_n == 1'b0) & (icmp_ln129_fu_422_p2 == 1'd1)) | ((mergeKipadStrm_empty_n == 1'b0) & (ap_predicate_op80_read_state6 == 1'b1)));
end

always @ (*) begin
    ap_condition_508 = ((cmp281_fu_533_p2 == 1'd1) & (cmp275_fu_528_p2 == 1'd0) & (icmp_ln215_fu_543_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_513 = ((cmp298_fu_538_p2 == 1'd0) & (cmp281_fu_533_p2 == 1'd0) & (cmp275_fu_528_p2 == 1'd0) & (icmp_ln215_fu_543_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_516 = ((cmp298_fu_538_p2 == 1'd1) & (cmp281_fu_533_p2 == 1'd0) & (cmp275_fu_528_p2 == 1'd0) & (icmp_ln215_fu_543_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_530 = ((cmp298_reg_1261 == 1'd0) & (cmp281_reg_1257 == 1'd0) & (or_ln223_fu_611_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_534 = ((cmp298_reg_1261 == 1'd1) & (cmp281_reg_1257 == 1'd0) & (or_ln223_fu_611_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op162_read_state20 = ((cmp275_fu_528_p2 == 1'd0) & (icmp_ln215_fu_543_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op207_write_state23 = ((icmp_ln152_reg_961 == 1'd0) & (icmp_ln129_reg_957 == 1'd0));
end

always @ (*) begin
    ap_predicate_op80_read_state6 = ((icmp_ln152_fu_427_p2 == 1'd0) & (icmp_ln129_fu_422_p2 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign blk_num_fu_379_p2 = (select_ln95_fu_372_p3 + zext_ln95_1_fu_369_p1);

assign cmp275_fu_528_p2 = ((trunc_ln91_reg_925 == 2'd0) ? 1'b1 : 1'b0);

assign cmp281_fu_533_p2 = ((trunc_ln91_reg_925 == 2'd1) ? 1'b1 : 1'b0);

assign cmp298_fu_538_p2 = ((trunc_ln91_reg_925 == 2'd2) ? 1'b1 : 1'b0);

assign empty_64_fu_476_p1 = mergeKipadStrm_dout[7:0];

assign empty_65_fu_480_p1 = mergeKipadStrm_dout[7:0];

assign empty_66_fu_484_p1 = mergeKipadStrm_dout[7:0];

assign empty_67_fu_488_p1 = mergeKipadStrm_dout[7:0];

assign empty_68_fu_492_p1 = mergeKipadStrm_dout[7:0];

assign empty_69_fu_496_p1 = mergeKipadStrm_dout[7:0];

assign empty_70_fu_500_p1 = mergeKipadStrm_dout[7:0];

assign empty_71_fu_504_p1 = mergeKipadStrm_dout[7:0];

assign empty_72_fu_508_p1 = mergeKipadStrm_dout[7:0];

assign empty_73_fu_512_p1 = mergeKipadStrm_dout[7:0];

assign empty_74_fu_516_p1 = mergeKipadStrm_dout[7:0];

assign empty_75_fu_520_p1 = mergeKipadStrm_dout[7:0];

assign empty_76_fu_524_p1 = mergeKipadStrm_dout[7:0];

assign empty_77_fu_590_p1 = mergeKipadStrm_dout[7:0];

assign empty_fu_442_p1 = mergeKipadStrm_dout[7:0];

assign grp_fu_302_p4 = {{mergeKipadStrm_dout[31:24]}};

assign grp_fu_312_p4 = {{mergeKipadStrm_dout[15:8]}};

assign grp_fu_322_p4 = {{mergeKipadStrm_dout[23:16]}};

assign grp_fu_332_p4 = {{len_reg_919[60:29]}};

assign grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_ap_start_reg;

assign grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start = grp_preProcessing_Pipeline_LOOP_SHA256_GEN_FULL_BLKS_fu_271_ap_start_reg;

assign icmp_ln129_fu_422_p2 = ((left_reg_933 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln152_fu_427_p2 = ((left_reg_933 < 6'd56) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_543_p2 = ((p_cast_reg_965 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln223_fu_606_p2 = ((p_cast_reg_965 != 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_363_p2 = ((left_fu_345_p1 > 6'd55) ? 1'b1 : 1'b0);

assign l_43_fu_594_p5 = {{{{empty_77_fu_590_p1}, {grp_fu_312_p4}}, {grp_fu_322_p4}}, {grp_fu_302_p4}};

assign left_fu_345_p1 = mergeKipadLenStrm_dout[5:0];

assign nblk_strm_din = blk_num_fu_379_p2;

assign or_ln151_1_fu_464_p5 = {{{{trunc_ln264_reg_939}, {3'd0}}, {grp_fu_332_p4}}, {448'd2147483648}};

assign or_ln203_s_fu_792_p18 = {{{{{{{{{{{{{{{{{trunc_ln264_reg_939}, {3'd0}}, {grp_fu_332_p4}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_16_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_15_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_14_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_13_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_12_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_11_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_10_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_9_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_8_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_7_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_6_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_5_out}}, 
    {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_4_out}}, {grp_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE_fu_280_b_out}};

assign or_ln223_fu_611_p2 = (icmp_ln223_reg_1288 | cmp275_reg_1252);

assign or_ln235_1_fu_656_p3 = {{trunc_ln234_1_fu_652_p1}, {24'd8388608}};

assign or_ln240_1_fu_642_p4 = {{{trunc_ln240_1_fu_638_p1}, {grp_fu_312_p4}}, {16'd32768}};

assign or_ln245_2_fu_626_p5 = {{{{trunc_ln245_1_fu_622_p1}, {grp_fu_312_p4}}, {grp_fu_322_p4}}, {8'd128}};

assign or_ln250_s_fu_664_p59 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{storemerge93_reg_258}, {b225_0_14_load_reg_240}}, {empty_76_reg_1232}}, {p_107_reg_1242}}, {p_108_reg_1247}}, {p_106_reg_1237}}, {empty_75_reg_1212}}, {p_104_reg_1222}}, {p_105_reg_1227}}, {p_103_reg_1217}}, {empty_74_reg_1192}}, {p_101_reg_1202}}, {p_102_reg_1207}}, {p_100_reg_1197}}, {empty_73_reg_1172}}, {p_98_reg_1182}}, {p_99_reg_1187}}, {p_97_reg_1177}}, {empty_72_reg_1152}}, {p_95_reg_1162}}, {p_96_reg_1167}}, {p_94_reg_1157}}, {empty_71_reg_1132}}, {p_92_reg_1142}}, {p_93_reg_1147}}, {p_91_reg_1137}}, {empty_70_reg_1112}}, {p_89_reg_1122}}, {p_90_reg_1127}}, {p_88_reg_1117}}, {empty_69_reg_1092}}, {p_86_reg_1102}}, {p_87_reg_1107}}, {p_85_reg_1097}}, {empty_68_reg_1072}}, {p_83_reg_1082}}, {p_84_reg_1087}}, {p_82_reg_1077}}, {empty_67_reg_1052}}, {p_80_reg_1062}}, {p_81_reg_1067}}, {p_79_reg_1057}}, {empty_66_reg_1032}}, {p_77_reg_1042}}, {p_78_reg_1047}}, {p_76_reg_1037}}, {empty_65_reg_1012}}, {p_74_reg_1022}}, {p_75_reg_1027}}, {p_73_reg_1017}}, 
    {empty_64_reg_992}}, {p_71_reg_1002}}, {p_72_reg_1007}}, {p_70_reg_997}}, {empty_reg_972}}, {p_68_reg_982}}, {p_69_reg_987}}, {p_s_reg_977}};

assign or_ln268_s_fu_729_p5 = {{{{trunc_ln264_reg_939}, {3'd0}}, {tmp_7_reg_1317}}, {448'd0}};

assign or_ln3_fu_568_p4 = {{{trunc_ln240_fu_564_p1}, {grp_fu_312_p4}}, {16'd32768}};

assign or_ln4_fu_552_p5 = {{{{trunc_ln245_fu_548_p1}, {grp_fu_312_p4}}, {grp_fu_322_p4}}, {8'd128}};

assign or_ln_fu_582_p3 = {{trunc_ln234_fu_578_p1}, {24'd8388608}};

assign select_ln223_fu_615_p3 = ((icmp_ln223_reg_1288[0:0] == 1'b1) ? 32'd0 : 32'd2147483648);

assign select_ln95_fu_372_p3 = ((icmp_ln95_reg_952[0:0] == 1'b1) ? 59'd2 : 59'd1);

assign start_out = real_start;

assign trunc_ln234_1_fu_652_p1 = mergeKipadStrm_dout[7:0];

assign trunc_ln234_fu_578_p1 = mergeKipadStrm_dout[7:0];

assign trunc_ln240_1_fu_638_p1 = mergeKipadStrm_dout[7:0];

assign trunc_ln240_fu_564_p1 = mergeKipadStrm_dout[7:0];

assign trunc_ln245_1_fu_622_p1 = mergeKipadStrm_dout[7:0];

assign trunc_ln245_fu_548_p1 = mergeKipadStrm_dout[7:0];

assign trunc_ln264_fu_349_p1 = mergeKipadLenStrm_dout[28:0];

assign trunc_ln91_fu_341_p1 = mergeKipadLenStrm_dout[1:0];

assign zext_ln95_1_fu_369_p1 = trunc_ln_reg_946;

always @ (posedge ap_clk) begin
    storemerge93_reg_258[6:0] <= 7'b0000000;
end

endmodule //test_hmac_sha256_preProcessing
