// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_hmac_sha256_kpad_32_64_256_32_64_sha256_wrapper_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        keyStrm_dout,
        keyStrm_empty_n,
        keyStrm_read,
        eLenStrm_dout,
        eLenStrm_empty_n,
        eLenStrm_read,
        kipadStrm_din,
        kipadStrm_full_n,
        kipadStrm_write,
        kipadStrm_num_data_valid,
        kipadStrm_fifo_cap,
        kopadStrm_din,
        kopadStrm_full_n,
        kopadStrm_write,
        kopadStrm_num_data_valid,
        kopadStrm_fifo_cap,
        eKipadStrm_din,
        eKipadStrm_full_n,
        eKipadStrm_write,
        eKipadStrm_num_data_valid,
        eKipadStrm_fifo_cap
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] keyStrm_dout;
input   keyStrm_empty_n;
output   keyStrm_read;
input  [0:0] eLenStrm_dout;
input   eLenStrm_empty_n;
output   eLenStrm_read;
output  [511:0] kipadStrm_din;
input   kipadStrm_full_n;
output   kipadStrm_write;
input  [2:0] kipadStrm_num_data_valid;
input  [2:0] kipadStrm_fifo_cap;
output  [511:0] kopadStrm_din;
input   kopadStrm_full_n;
output   kopadStrm_write;
input  [2:0] kopadStrm_num_data_valid;
input  [2:0] kopadStrm_fifo_cap;
output  [0:0] eKipadStrm_din;
input   eKipadStrm_full_n;
output   eKipadStrm_write;
input  [2:0] eKipadStrm_num_data_valid;
input  [2:0] eKipadStrm_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg eLenStrm_read;
reg kipadStrm_write;
reg kopadStrm_write;
reg[0:0] eKipadStrm_din;
reg eKipadStrm_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    eLenStrm_blk_n;
wire    ap_CS_fsm_state2;
reg    kipadStrm_blk_n;
wire    ap_CS_fsm_state5;
reg    kopadStrm_blk_n;
reg    eKipadStrm_blk_n;
wire   [0:0] eLenStrm_read_read_fu_186_p2;
wire    grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start;
wire    grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_done;
wire    grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_idle;
wire    grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_ready;
wire    grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_keyStrm_read;
wire   [511:0] grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out;
wire    grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out_ap_vld;
reg    grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_block_state2;
reg    ap_block_state5;
wire   [7:0] tmp_s_fu_249_p3;
wire   [7:0] tmp_2_fu_269_p3;
wire   [7:0] tmp_3_fu_289_p3;
wire   [7:0] tmp_4_fu_309_p3;
wire   [7:0] tmp_5_fu_329_p3;
wire   [7:0] tmp_6_fu_349_p3;
wire   [7:0] tmp_7_fu_369_p3;
wire   [7:0] tmp_8_fu_389_p3;
wire   [7:0] tmp_9_fu_409_p3;
wire   [7:0] tmp_10_fu_429_p3;
wire   [7:0] tmp_11_fu_449_p3;
wire   [7:0] tmp_12_fu_469_p3;
wire   [7:0] tmp_13_fu_489_p3;
wire   [7:0] tmp_14_fu_509_p3;
wire   [7:0] tmp_15_fu_529_p3;
wire   [7:0] tmp_16_fu_549_p3;
wire   [7:0] tmp_17_fu_569_p3;
wire   [7:0] tmp_18_fu_589_p3;
wire   [7:0] tmp_19_fu_609_p3;
wire   [7:0] tmp_20_fu_629_p3;
wire   [7:0] tmp_21_fu_649_p3;
wire   [7:0] tmp_22_fu_669_p3;
wire   [7:0] tmp_23_fu_689_p3;
wire   [7:0] tmp_24_fu_709_p3;
wire   [7:0] tmp_25_fu_729_p3;
wire   [7:0] tmp_26_fu_749_p3;
wire   [7:0] tmp_27_fu_769_p3;
wire   [7:0] tmp_28_fu_789_p3;
wire   [7:0] tmp_29_fu_809_p3;
wire   [7:0] tmp_30_fu_829_p3;
wire   [7:0] tmp_31_fu_849_p3;
wire   [7:0] tmp_32_fu_869_p3;
wire   [7:0] tmp_33_fu_889_p3;
wire   [7:0] tmp_34_fu_909_p3;
wire   [7:0] tmp_35_fu_929_p3;
wire   [7:0] tmp_36_fu_949_p3;
wire   [7:0] tmp_37_fu_969_p3;
wire   [7:0] tmp_38_fu_989_p3;
wire   [7:0] tmp_39_fu_1009_p3;
wire   [7:0] tmp_40_fu_1029_p3;
wire   [7:0] tmp_41_fu_1049_p3;
wire   [7:0] tmp_42_fu_1069_p3;
wire   [7:0] tmp_43_fu_1089_p3;
wire   [7:0] tmp_44_fu_1109_p3;
wire   [7:0] tmp_45_fu_1129_p3;
wire   [7:0] tmp_46_fu_1149_p3;
wire   [7:0] tmp_47_fu_1169_p3;
wire   [7:0] tmp_48_fu_1189_p3;
wire   [7:0] tmp_49_fu_1209_p3;
wire   [7:0] tmp_50_fu_1229_p3;
wire   [7:0] tmp_51_fu_1249_p3;
wire   [7:0] tmp_52_fu_1269_p3;
wire   [7:0] tmp_53_fu_1289_p3;
wire   [7:0] tmp_54_fu_1309_p3;
wire   [7:0] tmp_55_fu_1329_p3;
wire   [7:0] tmp_56_fu_1349_p3;
wire   [7:0] tmp_57_fu_1369_p3;
wire   [7:0] tmp_58_fu_1389_p3;
wire   [7:0] tmp_59_fu_1409_p3;
wire   [7:0] tmp_60_fu_1429_p3;
wire   [7:0] tmp_61_fu_1449_p3;
wire   [7:0] tmp_62_fu_1469_p3;
wire   [7:0] tmp_63_fu_1489_p3;
wire   [7:0] xor_ln131_62_fu_1497_p2;
wire   [7:0] xor_ln131_61_fu_1477_p2;
wire   [7:0] xor_ln131_60_fu_1457_p2;
wire   [7:0] xor_ln131_59_fu_1437_p2;
wire   [7:0] xor_ln131_58_fu_1417_p2;
wire   [7:0] xor_ln131_57_fu_1397_p2;
wire   [7:0] xor_ln131_56_fu_1377_p2;
wire   [7:0] xor_ln131_55_fu_1357_p2;
wire   [7:0] xor_ln131_54_fu_1337_p2;
wire   [7:0] xor_ln131_53_fu_1317_p2;
wire   [7:0] xor_ln131_52_fu_1297_p2;
wire   [7:0] xor_ln131_51_fu_1277_p2;
wire   [7:0] xor_ln131_50_fu_1257_p2;
wire   [7:0] xor_ln131_49_fu_1237_p2;
wire   [7:0] xor_ln131_48_fu_1217_p2;
wire   [7:0] xor_ln131_47_fu_1197_p2;
wire   [7:0] xor_ln131_46_fu_1177_p2;
wire   [7:0] xor_ln131_45_fu_1157_p2;
wire   [7:0] xor_ln131_44_fu_1137_p2;
wire   [7:0] xor_ln131_43_fu_1117_p2;
wire   [7:0] xor_ln131_42_fu_1097_p2;
wire   [7:0] xor_ln131_41_fu_1077_p2;
wire   [7:0] xor_ln131_40_fu_1057_p2;
wire   [7:0] xor_ln131_39_fu_1037_p2;
wire   [7:0] xor_ln131_38_fu_1017_p2;
wire   [7:0] xor_ln131_37_fu_997_p2;
wire   [7:0] xor_ln131_36_fu_977_p2;
wire   [7:0] xor_ln131_35_fu_957_p2;
wire   [7:0] xor_ln131_34_fu_937_p2;
wire   [7:0] xor_ln131_33_fu_917_p2;
wire   [7:0] xor_ln131_32_fu_897_p2;
wire   [7:0] xor_ln131_31_fu_877_p2;
wire   [7:0] xor_ln131_30_fu_857_p2;
wire   [7:0] xor_ln131_29_fu_837_p2;
wire   [7:0] xor_ln131_28_fu_817_p2;
wire   [7:0] xor_ln131_27_fu_797_p2;
wire   [7:0] xor_ln131_26_fu_777_p2;
wire   [7:0] xor_ln131_25_fu_757_p2;
wire   [7:0] xor_ln131_24_fu_737_p2;
wire   [7:0] xor_ln131_23_fu_717_p2;
wire   [7:0] xor_ln131_22_fu_697_p2;
wire   [7:0] xor_ln131_21_fu_677_p2;
wire   [7:0] xor_ln131_20_fu_657_p2;
wire   [7:0] xor_ln131_19_fu_637_p2;
wire   [7:0] xor_ln131_18_fu_617_p2;
wire   [7:0] xor_ln131_17_fu_597_p2;
wire   [7:0] xor_ln131_16_fu_577_p2;
wire   [7:0] xor_ln131_15_fu_557_p2;
wire   [7:0] xor_ln131_14_fu_537_p2;
wire   [7:0] xor_ln131_13_fu_517_p2;
wire   [7:0] xor_ln131_12_fu_497_p2;
wire   [7:0] xor_ln131_11_fu_477_p2;
wire   [7:0] xor_ln131_10_fu_457_p2;
wire   [7:0] xor_ln131_9_fu_437_p2;
wire   [7:0] xor_ln131_8_fu_417_p2;
wire   [7:0] xor_ln131_7_fu_397_p2;
wire   [7:0] xor_ln131_6_fu_377_p2;
wire   [7:0] xor_ln131_5_fu_357_p2;
wire   [7:0] xor_ln131_4_fu_337_p2;
wire   [7:0] xor_ln131_3_fu_317_p2;
wire   [7:0] xor_ln131_2_fu_297_p2;
wire   [7:0] xor_ln131_1_fu_277_p2;
wire   [7:0] xor_ln131_fu_257_p2;
wire   [7:0] xor_ln132_62_fu_1636_p2;
wire   [7:0] xor_ln132_61_fu_1483_p2;
wire   [7:0] xor_ln132_60_fu_1463_p2;
wire   [7:0] xor_ln132_59_fu_1443_p2;
wire   [7:0] xor_ln132_58_fu_1423_p2;
wire   [7:0] xor_ln132_57_fu_1403_p2;
wire   [7:0] xor_ln132_56_fu_1383_p2;
wire   [7:0] xor_ln132_55_fu_1363_p2;
wire   [7:0] xor_ln132_54_fu_1343_p2;
wire   [7:0] xor_ln132_53_fu_1323_p2;
wire   [7:0] xor_ln132_52_fu_1303_p2;
wire   [7:0] xor_ln132_51_fu_1283_p2;
wire   [7:0] xor_ln132_50_fu_1263_p2;
wire   [7:0] xor_ln132_49_fu_1243_p2;
wire   [7:0] xor_ln132_48_fu_1223_p2;
wire   [7:0] xor_ln132_47_fu_1203_p2;
wire   [7:0] xor_ln132_46_fu_1183_p2;
wire   [7:0] xor_ln132_45_fu_1163_p2;
wire   [7:0] xor_ln132_44_fu_1143_p2;
wire   [7:0] xor_ln132_43_fu_1123_p2;
wire   [7:0] xor_ln132_42_fu_1103_p2;
wire   [7:0] xor_ln132_41_fu_1083_p2;
wire   [7:0] xor_ln132_40_fu_1063_p2;
wire   [7:0] xor_ln132_39_fu_1043_p2;
wire   [7:0] xor_ln132_38_fu_1023_p2;
wire   [7:0] xor_ln132_37_fu_1003_p2;
wire   [7:0] xor_ln132_36_fu_983_p2;
wire   [7:0] xor_ln132_35_fu_963_p2;
wire   [7:0] xor_ln132_34_fu_943_p2;
wire   [7:0] xor_ln132_33_fu_923_p2;
wire   [7:0] xor_ln132_32_fu_903_p2;
wire   [7:0] xor_ln132_31_fu_883_p2;
wire   [7:0] xor_ln132_30_fu_863_p2;
wire   [7:0] xor_ln132_29_fu_843_p2;
wire   [7:0] xor_ln132_28_fu_823_p2;
wire   [7:0] xor_ln132_27_fu_803_p2;
wire   [7:0] xor_ln132_26_fu_783_p2;
wire   [7:0] xor_ln132_25_fu_763_p2;
wire   [7:0] xor_ln132_24_fu_743_p2;
wire   [7:0] xor_ln132_23_fu_723_p2;
wire   [7:0] xor_ln132_22_fu_703_p2;
wire   [7:0] xor_ln132_21_fu_683_p2;
wire   [7:0] xor_ln132_20_fu_663_p2;
wire   [7:0] xor_ln132_19_fu_643_p2;
wire   [7:0] xor_ln132_18_fu_623_p2;
wire   [7:0] xor_ln132_17_fu_603_p2;
wire   [7:0] xor_ln132_16_fu_583_p2;
wire   [7:0] xor_ln132_15_fu_563_p2;
wire   [7:0] xor_ln132_14_fu_543_p2;
wire   [7:0] xor_ln132_13_fu_523_p2;
wire   [7:0] xor_ln132_12_fu_503_p2;
wire   [7:0] xor_ln132_11_fu_483_p2;
wire   [7:0] xor_ln132_10_fu_463_p2;
wire   [7:0] xor_ln132_9_fu_443_p2;
wire   [7:0] xor_ln132_8_fu_423_p2;
wire   [7:0] xor_ln132_7_fu_403_p2;
wire   [7:0] xor_ln132_6_fu_383_p2;
wire   [7:0] xor_ln132_5_fu_363_p2;
wire   [7:0] xor_ln132_4_fu_343_p2;
wire   [7:0] xor_ln132_3_fu_323_p2;
wire   [7:0] xor_ln132_2_fu_303_p2;
wire   [7:0] xor_ln132_1_fu_283_p2;
wire   [7:0] xor_ln132_fu_263_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start_reg = 1'b0;
end

test_hmac_sha256_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2 grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start),
    .ap_done(grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_done),
    .ap_idle(grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_idle),
    .ap_ready(grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_ready),
    .keyStrm_dout(keyStrm_dout),
    .keyStrm_empty_n(keyStrm_empty_n),
    .keyStrm_read(grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_keyStrm_read),
    .k1_out(grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out),
    .k1_out_ap_vld(grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((eLenStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start_reg <= 1'b1;
        end else if ((grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_ready == 1'b1)) begin
            grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((eLenStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((eLenStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        eKipadStrm_blk_n = eKipadStrm_full_n;
    end else begin
        eKipadStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        eKipadStrm_din = 1'd0;
    end else if (((eLenStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        eKipadStrm_din = 1'd1;
    end else begin
        eKipadStrm_din = 'bx;
    end
end

always @ (*) begin
    if ((((eLenStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2)) | ((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5)))) begin
        eKipadStrm_write = 1'b1;
    end else begin
        eKipadStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        eLenStrm_blk_n = eLenStrm_empty_n;
    end else begin
        eLenStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        eLenStrm_read = 1'b1;
    end else begin
        eLenStrm_read = 1'b0;
    end
end

always @ (*) begin
    if (((eLenStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kipadStrm_blk_n = kipadStrm_full_n;
    end else begin
        kipadStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        kipadStrm_write = 1'b1;
    end else begin
        kipadStrm_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kopadStrm_blk_n = kopadStrm_full_n;
    end else begin
        kopadStrm_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        kopadStrm_write = 1'b1;
    end else begin
        kopadStrm_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((eLenStrm_dout == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((eLenStrm_read_read_fu_186_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((eLenStrm_empty_n == 1'b0) | ((eLenStrm_dout == 1'd1) & (eKipadStrm_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5 = ((eKipadStrm_full_n == 1'b0) | (kopadStrm_full_n == 1'b0) | (kipadStrm_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign eLenStrm_read_read_fu_186_p2 = eLenStrm_dout;

assign grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start = grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_ap_start_reg;

assign keyStrm_read = grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_keyStrm_read;

assign kipadStrm_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{xor_ln131_62_fu_1497_p2}, {xor_ln131_61_fu_1477_p2}}, {xor_ln131_60_fu_1457_p2}}, {xor_ln131_59_fu_1437_p2}}, {xor_ln131_58_fu_1417_p2}}, {xor_ln131_57_fu_1397_p2}}, {xor_ln131_56_fu_1377_p2}}, {xor_ln131_55_fu_1357_p2}}, {xor_ln131_54_fu_1337_p2}}, {xor_ln131_53_fu_1317_p2}}, {xor_ln131_52_fu_1297_p2}}, {xor_ln131_51_fu_1277_p2}}, {xor_ln131_50_fu_1257_p2}}, {xor_ln131_49_fu_1237_p2}}, {xor_ln131_48_fu_1217_p2}}, {xor_ln131_47_fu_1197_p2}}, {xor_ln131_46_fu_1177_p2}}, {xor_ln131_45_fu_1157_p2}}, {xor_ln131_44_fu_1137_p2}}, {xor_ln131_43_fu_1117_p2}}, {xor_ln131_42_fu_1097_p2}}, {xor_ln131_41_fu_1077_p2}}, {xor_ln131_40_fu_1057_p2}}, {xor_ln131_39_fu_1037_p2}}, {xor_ln131_38_fu_1017_p2}}, {xor_ln131_37_fu_997_p2}}, {xor_ln131_36_fu_977_p2}}, {xor_ln131_35_fu_957_p2}}, {xor_ln131_34_fu_937_p2}}, {xor_ln131_33_fu_917_p2}}, {xor_ln131_32_fu_897_p2}}, {xor_ln131_31_fu_877_p2}}, {xor_ln131_30_fu_857_p2}}, {xor_ln131_29_fu_837_p2}}, {xor_ln131_28_fu_817_p2}}, 
    {xor_ln131_27_fu_797_p2}}, {xor_ln131_26_fu_777_p2}}, {xor_ln131_25_fu_757_p2}}, {xor_ln131_24_fu_737_p2}}, {xor_ln131_23_fu_717_p2}}, {xor_ln131_22_fu_697_p2}}, {xor_ln131_21_fu_677_p2}}, {xor_ln131_20_fu_657_p2}}, {xor_ln131_19_fu_637_p2}}, {xor_ln131_18_fu_617_p2}}, {xor_ln131_17_fu_597_p2}}, {xor_ln131_16_fu_577_p2}}, {xor_ln131_15_fu_557_p2}}, {xor_ln131_14_fu_537_p2}}, {xor_ln131_13_fu_517_p2}}, {xor_ln131_12_fu_497_p2}}, {xor_ln131_11_fu_477_p2}}, {xor_ln131_10_fu_457_p2}}, {xor_ln131_9_fu_437_p2}}, {xor_ln131_8_fu_417_p2}}, {xor_ln131_7_fu_397_p2}}, {xor_ln131_6_fu_377_p2}}, {xor_ln131_5_fu_357_p2}}, {xor_ln131_4_fu_337_p2}}, {xor_ln131_3_fu_317_p2}}, {xor_ln131_2_fu_297_p2}}, {xor_ln131_1_fu_277_p2}}, {xor_ln131_fu_257_p2}}, {8'd54}};

assign kopadStrm_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{xor_ln132_62_fu_1636_p2}, {xor_ln132_61_fu_1483_p2}}, {xor_ln132_60_fu_1463_p2}}, {xor_ln132_59_fu_1443_p2}}, {xor_ln132_58_fu_1423_p2}}, {xor_ln132_57_fu_1403_p2}}, {xor_ln132_56_fu_1383_p2}}, {xor_ln132_55_fu_1363_p2}}, {xor_ln132_54_fu_1343_p2}}, {xor_ln132_53_fu_1323_p2}}, {xor_ln132_52_fu_1303_p2}}, {xor_ln132_51_fu_1283_p2}}, {xor_ln132_50_fu_1263_p2}}, {xor_ln132_49_fu_1243_p2}}, {xor_ln132_48_fu_1223_p2}}, {xor_ln132_47_fu_1203_p2}}, {xor_ln132_46_fu_1183_p2}}, {xor_ln132_45_fu_1163_p2}}, {xor_ln132_44_fu_1143_p2}}, {xor_ln132_43_fu_1123_p2}}, {xor_ln132_42_fu_1103_p2}}, {xor_ln132_41_fu_1083_p2}}, {xor_ln132_40_fu_1063_p2}}, {xor_ln132_39_fu_1043_p2}}, {xor_ln132_38_fu_1023_p2}}, {xor_ln132_37_fu_1003_p2}}, {xor_ln132_36_fu_983_p2}}, {xor_ln132_35_fu_963_p2}}, {xor_ln132_34_fu_943_p2}}, {xor_ln132_33_fu_923_p2}}, {xor_ln132_32_fu_903_p2}}, {xor_ln132_31_fu_883_p2}}, {xor_ln132_30_fu_863_p2}}, {xor_ln132_29_fu_843_p2}}, {xor_ln132_28_fu_823_p2}}, 
    {xor_ln132_27_fu_803_p2}}, {xor_ln132_26_fu_783_p2}}, {xor_ln132_25_fu_763_p2}}, {xor_ln132_24_fu_743_p2}}, {xor_ln132_23_fu_723_p2}}, {xor_ln132_22_fu_703_p2}}, {xor_ln132_21_fu_683_p2}}, {xor_ln132_20_fu_663_p2}}, {xor_ln132_19_fu_643_p2}}, {xor_ln132_18_fu_623_p2}}, {xor_ln132_17_fu_603_p2}}, {xor_ln132_16_fu_583_p2}}, {xor_ln132_15_fu_563_p2}}, {xor_ln132_14_fu_543_p2}}, {xor_ln132_13_fu_523_p2}}, {xor_ln132_12_fu_503_p2}}, {xor_ln132_11_fu_483_p2}}, {xor_ln132_10_fu_463_p2}}, {xor_ln132_9_fu_443_p2}}, {xor_ln132_8_fu_423_p2}}, {xor_ln132_7_fu_403_p2}}, {xor_ln132_6_fu_383_p2}}, {xor_ln132_5_fu_363_p2}}, {xor_ln132_4_fu_343_p2}}, {xor_ln132_3_fu_323_p2}}, {xor_ln132_2_fu_303_p2}}, {xor_ln132_1_fu_283_p2}}, {xor_ln132_fu_263_p2}}, {8'd92}};

assign start_out = real_start;

assign tmp_10_fu_429_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[87:80]}};

assign tmp_11_fu_449_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[95:88]}};

assign tmp_12_fu_469_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[103:96]}};

assign tmp_13_fu_489_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[111:104]}};

assign tmp_14_fu_509_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[119:112]}};

assign tmp_15_fu_529_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[127:120]}};

assign tmp_16_fu_549_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[135:128]}};

assign tmp_17_fu_569_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[143:136]}};

assign tmp_18_fu_589_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[151:144]}};

assign tmp_19_fu_609_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[159:152]}};

assign tmp_20_fu_629_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[167:160]}};

assign tmp_21_fu_649_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[175:168]}};

assign tmp_22_fu_669_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[183:176]}};

assign tmp_23_fu_689_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[191:184]}};

assign tmp_24_fu_709_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[199:192]}};

assign tmp_25_fu_729_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[207:200]}};

assign tmp_26_fu_749_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[215:208]}};

assign tmp_27_fu_769_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[223:216]}};

assign tmp_28_fu_789_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[231:224]}};

assign tmp_29_fu_809_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[239:232]}};

assign tmp_2_fu_269_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[23:16]}};

assign tmp_30_fu_829_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[247:240]}};

assign tmp_31_fu_849_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[255:248]}};

assign tmp_32_fu_869_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[263:256]}};

assign tmp_33_fu_889_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[271:264]}};

assign tmp_34_fu_909_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[279:272]}};

assign tmp_35_fu_929_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[287:280]}};

assign tmp_36_fu_949_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[295:288]}};

assign tmp_37_fu_969_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[303:296]}};

assign tmp_38_fu_989_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[311:304]}};

assign tmp_39_fu_1009_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[319:312]}};

assign tmp_3_fu_289_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[31:24]}};

assign tmp_40_fu_1029_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[327:320]}};

assign tmp_41_fu_1049_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[335:328]}};

assign tmp_42_fu_1069_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[343:336]}};

assign tmp_43_fu_1089_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[351:344]}};

assign tmp_44_fu_1109_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[359:352]}};

assign tmp_45_fu_1129_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[367:360]}};

assign tmp_46_fu_1149_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[375:368]}};

assign tmp_47_fu_1169_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[383:376]}};

assign tmp_48_fu_1189_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[391:384]}};

assign tmp_49_fu_1209_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[399:392]}};

assign tmp_4_fu_309_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[39:32]}};

assign tmp_50_fu_1229_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[407:400]}};

assign tmp_51_fu_1249_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[415:408]}};

assign tmp_52_fu_1269_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[423:416]}};

assign tmp_53_fu_1289_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[431:424]}};

assign tmp_54_fu_1309_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[439:432]}};

assign tmp_55_fu_1329_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[447:440]}};

assign tmp_56_fu_1349_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[455:448]}};

assign tmp_57_fu_1369_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[463:456]}};

assign tmp_58_fu_1389_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[471:464]}};

assign tmp_59_fu_1409_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[479:472]}};

assign tmp_5_fu_329_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[47:40]}};

assign tmp_60_fu_1429_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[487:480]}};

assign tmp_61_fu_1449_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[495:488]}};

assign tmp_62_fu_1469_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[503:496]}};

assign tmp_63_fu_1489_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[511:504]}};

assign tmp_6_fu_349_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[55:48]}};

assign tmp_7_fu_369_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[63:56]}};

assign tmp_8_fu_389_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[71:64]}};

assign tmp_9_fu_409_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[79:72]}};

assign tmp_s_fu_249_p3 = {{grp_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2_fu_215_k1_out[15:8]}};

assign xor_ln131_10_fu_457_p2 = (tmp_11_fu_449_p3 ^ 8'd54);

assign xor_ln131_11_fu_477_p2 = (tmp_12_fu_469_p3 ^ 8'd54);

assign xor_ln131_12_fu_497_p2 = (tmp_13_fu_489_p3 ^ 8'd54);

assign xor_ln131_13_fu_517_p2 = (tmp_14_fu_509_p3 ^ 8'd54);

assign xor_ln131_14_fu_537_p2 = (tmp_15_fu_529_p3 ^ 8'd54);

assign xor_ln131_15_fu_557_p2 = (tmp_16_fu_549_p3 ^ 8'd54);

assign xor_ln131_16_fu_577_p2 = (tmp_17_fu_569_p3 ^ 8'd54);

assign xor_ln131_17_fu_597_p2 = (tmp_18_fu_589_p3 ^ 8'd54);

assign xor_ln131_18_fu_617_p2 = (tmp_19_fu_609_p3 ^ 8'd54);

assign xor_ln131_19_fu_637_p2 = (tmp_20_fu_629_p3 ^ 8'd54);

assign xor_ln131_1_fu_277_p2 = (tmp_2_fu_269_p3 ^ 8'd54);

assign xor_ln131_20_fu_657_p2 = (tmp_21_fu_649_p3 ^ 8'd54);

assign xor_ln131_21_fu_677_p2 = (tmp_22_fu_669_p3 ^ 8'd54);

assign xor_ln131_22_fu_697_p2 = (tmp_23_fu_689_p3 ^ 8'd54);

assign xor_ln131_23_fu_717_p2 = (tmp_24_fu_709_p3 ^ 8'd54);

assign xor_ln131_24_fu_737_p2 = (tmp_25_fu_729_p3 ^ 8'd54);

assign xor_ln131_25_fu_757_p2 = (tmp_26_fu_749_p3 ^ 8'd54);

assign xor_ln131_26_fu_777_p2 = (tmp_27_fu_769_p3 ^ 8'd54);

assign xor_ln131_27_fu_797_p2 = (tmp_28_fu_789_p3 ^ 8'd54);

assign xor_ln131_28_fu_817_p2 = (tmp_29_fu_809_p3 ^ 8'd54);

assign xor_ln131_29_fu_837_p2 = (tmp_30_fu_829_p3 ^ 8'd54);

assign xor_ln131_2_fu_297_p2 = (tmp_3_fu_289_p3 ^ 8'd54);

assign xor_ln131_30_fu_857_p2 = (tmp_31_fu_849_p3 ^ 8'd54);

assign xor_ln131_31_fu_877_p2 = (tmp_32_fu_869_p3 ^ 8'd54);

assign xor_ln131_32_fu_897_p2 = (tmp_33_fu_889_p3 ^ 8'd54);

assign xor_ln131_33_fu_917_p2 = (tmp_34_fu_909_p3 ^ 8'd54);

assign xor_ln131_34_fu_937_p2 = (tmp_35_fu_929_p3 ^ 8'd54);

assign xor_ln131_35_fu_957_p2 = (tmp_36_fu_949_p3 ^ 8'd54);

assign xor_ln131_36_fu_977_p2 = (tmp_37_fu_969_p3 ^ 8'd54);

assign xor_ln131_37_fu_997_p2 = (tmp_38_fu_989_p3 ^ 8'd54);

assign xor_ln131_38_fu_1017_p2 = (tmp_39_fu_1009_p3 ^ 8'd54);

assign xor_ln131_39_fu_1037_p2 = (tmp_40_fu_1029_p3 ^ 8'd54);

assign xor_ln131_3_fu_317_p2 = (tmp_4_fu_309_p3 ^ 8'd54);

assign xor_ln131_40_fu_1057_p2 = (tmp_41_fu_1049_p3 ^ 8'd54);

assign xor_ln131_41_fu_1077_p2 = (tmp_42_fu_1069_p3 ^ 8'd54);

assign xor_ln131_42_fu_1097_p2 = (tmp_43_fu_1089_p3 ^ 8'd54);

assign xor_ln131_43_fu_1117_p2 = (tmp_44_fu_1109_p3 ^ 8'd54);

assign xor_ln131_44_fu_1137_p2 = (tmp_45_fu_1129_p3 ^ 8'd54);

assign xor_ln131_45_fu_1157_p2 = (tmp_46_fu_1149_p3 ^ 8'd54);

assign xor_ln131_46_fu_1177_p2 = (tmp_47_fu_1169_p3 ^ 8'd54);

assign xor_ln131_47_fu_1197_p2 = (tmp_48_fu_1189_p3 ^ 8'd54);

assign xor_ln131_48_fu_1217_p2 = (tmp_49_fu_1209_p3 ^ 8'd54);

assign xor_ln131_49_fu_1237_p2 = (tmp_50_fu_1229_p3 ^ 8'd54);

assign xor_ln131_4_fu_337_p2 = (tmp_5_fu_329_p3 ^ 8'd54);

assign xor_ln131_50_fu_1257_p2 = (tmp_51_fu_1249_p3 ^ 8'd54);

assign xor_ln131_51_fu_1277_p2 = (tmp_52_fu_1269_p3 ^ 8'd54);

assign xor_ln131_52_fu_1297_p2 = (tmp_53_fu_1289_p3 ^ 8'd54);

assign xor_ln131_53_fu_1317_p2 = (tmp_54_fu_1309_p3 ^ 8'd54);

assign xor_ln131_54_fu_1337_p2 = (tmp_55_fu_1329_p3 ^ 8'd54);

assign xor_ln131_55_fu_1357_p2 = (tmp_56_fu_1349_p3 ^ 8'd54);

assign xor_ln131_56_fu_1377_p2 = (tmp_57_fu_1369_p3 ^ 8'd54);

assign xor_ln131_57_fu_1397_p2 = (tmp_58_fu_1389_p3 ^ 8'd54);

assign xor_ln131_58_fu_1417_p2 = (tmp_59_fu_1409_p3 ^ 8'd54);

assign xor_ln131_59_fu_1437_p2 = (tmp_60_fu_1429_p3 ^ 8'd54);

assign xor_ln131_5_fu_357_p2 = (tmp_6_fu_349_p3 ^ 8'd54);

assign xor_ln131_60_fu_1457_p2 = (tmp_61_fu_1449_p3 ^ 8'd54);

assign xor_ln131_61_fu_1477_p2 = (tmp_62_fu_1469_p3 ^ 8'd54);

assign xor_ln131_62_fu_1497_p2 = (tmp_63_fu_1489_p3 ^ 8'd54);

assign xor_ln131_6_fu_377_p2 = (tmp_7_fu_369_p3 ^ 8'd54);

assign xor_ln131_7_fu_397_p2 = (tmp_8_fu_389_p3 ^ 8'd54);

assign xor_ln131_8_fu_417_p2 = (tmp_9_fu_409_p3 ^ 8'd54);

assign xor_ln131_9_fu_437_p2 = (tmp_10_fu_429_p3 ^ 8'd54);

assign xor_ln131_fu_257_p2 = (tmp_s_fu_249_p3 ^ 8'd54);

assign xor_ln132_10_fu_463_p2 = (tmp_11_fu_449_p3 ^ 8'd92);

assign xor_ln132_11_fu_483_p2 = (tmp_12_fu_469_p3 ^ 8'd92);

assign xor_ln132_12_fu_503_p2 = (tmp_13_fu_489_p3 ^ 8'd92);

assign xor_ln132_13_fu_523_p2 = (tmp_14_fu_509_p3 ^ 8'd92);

assign xor_ln132_14_fu_543_p2 = (tmp_15_fu_529_p3 ^ 8'd92);

assign xor_ln132_15_fu_563_p2 = (tmp_16_fu_549_p3 ^ 8'd92);

assign xor_ln132_16_fu_583_p2 = (tmp_17_fu_569_p3 ^ 8'd92);

assign xor_ln132_17_fu_603_p2 = (tmp_18_fu_589_p3 ^ 8'd92);

assign xor_ln132_18_fu_623_p2 = (tmp_19_fu_609_p3 ^ 8'd92);

assign xor_ln132_19_fu_643_p2 = (tmp_20_fu_629_p3 ^ 8'd92);

assign xor_ln132_1_fu_283_p2 = (tmp_2_fu_269_p3 ^ 8'd92);

assign xor_ln132_20_fu_663_p2 = (tmp_21_fu_649_p3 ^ 8'd92);

assign xor_ln132_21_fu_683_p2 = (tmp_22_fu_669_p3 ^ 8'd92);

assign xor_ln132_22_fu_703_p2 = (tmp_23_fu_689_p3 ^ 8'd92);

assign xor_ln132_23_fu_723_p2 = (tmp_24_fu_709_p3 ^ 8'd92);

assign xor_ln132_24_fu_743_p2 = (tmp_25_fu_729_p3 ^ 8'd92);

assign xor_ln132_25_fu_763_p2 = (tmp_26_fu_749_p3 ^ 8'd92);

assign xor_ln132_26_fu_783_p2 = (tmp_27_fu_769_p3 ^ 8'd92);

assign xor_ln132_27_fu_803_p2 = (tmp_28_fu_789_p3 ^ 8'd92);

assign xor_ln132_28_fu_823_p2 = (tmp_29_fu_809_p3 ^ 8'd92);

assign xor_ln132_29_fu_843_p2 = (tmp_30_fu_829_p3 ^ 8'd92);

assign xor_ln132_2_fu_303_p2 = (tmp_3_fu_289_p3 ^ 8'd92);

assign xor_ln132_30_fu_863_p2 = (tmp_31_fu_849_p3 ^ 8'd92);

assign xor_ln132_31_fu_883_p2 = (tmp_32_fu_869_p3 ^ 8'd92);

assign xor_ln132_32_fu_903_p2 = (tmp_33_fu_889_p3 ^ 8'd92);

assign xor_ln132_33_fu_923_p2 = (tmp_34_fu_909_p3 ^ 8'd92);

assign xor_ln132_34_fu_943_p2 = (tmp_35_fu_929_p3 ^ 8'd92);

assign xor_ln132_35_fu_963_p2 = (tmp_36_fu_949_p3 ^ 8'd92);

assign xor_ln132_36_fu_983_p2 = (tmp_37_fu_969_p3 ^ 8'd92);

assign xor_ln132_37_fu_1003_p2 = (tmp_38_fu_989_p3 ^ 8'd92);

assign xor_ln132_38_fu_1023_p2 = (tmp_39_fu_1009_p3 ^ 8'd92);

assign xor_ln132_39_fu_1043_p2 = (tmp_40_fu_1029_p3 ^ 8'd92);

assign xor_ln132_3_fu_323_p2 = (tmp_4_fu_309_p3 ^ 8'd92);

assign xor_ln132_40_fu_1063_p2 = (tmp_41_fu_1049_p3 ^ 8'd92);

assign xor_ln132_41_fu_1083_p2 = (tmp_42_fu_1069_p3 ^ 8'd92);

assign xor_ln132_42_fu_1103_p2 = (tmp_43_fu_1089_p3 ^ 8'd92);

assign xor_ln132_43_fu_1123_p2 = (tmp_44_fu_1109_p3 ^ 8'd92);

assign xor_ln132_44_fu_1143_p2 = (tmp_45_fu_1129_p3 ^ 8'd92);

assign xor_ln132_45_fu_1163_p2 = (tmp_46_fu_1149_p3 ^ 8'd92);

assign xor_ln132_46_fu_1183_p2 = (tmp_47_fu_1169_p3 ^ 8'd92);

assign xor_ln132_47_fu_1203_p2 = (tmp_48_fu_1189_p3 ^ 8'd92);

assign xor_ln132_48_fu_1223_p2 = (tmp_49_fu_1209_p3 ^ 8'd92);

assign xor_ln132_49_fu_1243_p2 = (tmp_50_fu_1229_p3 ^ 8'd92);

assign xor_ln132_4_fu_343_p2 = (tmp_5_fu_329_p3 ^ 8'd92);

assign xor_ln132_50_fu_1263_p2 = (tmp_51_fu_1249_p3 ^ 8'd92);

assign xor_ln132_51_fu_1283_p2 = (tmp_52_fu_1269_p3 ^ 8'd92);

assign xor_ln132_52_fu_1303_p2 = (tmp_53_fu_1289_p3 ^ 8'd92);

assign xor_ln132_53_fu_1323_p2 = (tmp_54_fu_1309_p3 ^ 8'd92);

assign xor_ln132_54_fu_1343_p2 = (tmp_55_fu_1329_p3 ^ 8'd92);

assign xor_ln132_55_fu_1363_p2 = (tmp_56_fu_1349_p3 ^ 8'd92);

assign xor_ln132_56_fu_1383_p2 = (tmp_57_fu_1369_p3 ^ 8'd92);

assign xor_ln132_57_fu_1403_p2 = (tmp_58_fu_1389_p3 ^ 8'd92);

assign xor_ln132_58_fu_1423_p2 = (tmp_59_fu_1409_p3 ^ 8'd92);

assign xor_ln132_59_fu_1443_p2 = (tmp_60_fu_1429_p3 ^ 8'd92);

assign xor_ln132_5_fu_363_p2 = (tmp_6_fu_349_p3 ^ 8'd92);

assign xor_ln132_60_fu_1463_p2 = (tmp_61_fu_1449_p3 ^ 8'd92);

assign xor_ln132_61_fu_1483_p2 = (tmp_62_fu_1469_p3 ^ 8'd92);

assign xor_ln132_62_fu_1636_p2 = (tmp_63_fu_1489_p3 ^ 8'd92);

assign xor_ln132_6_fu_383_p2 = (tmp_7_fu_369_p3 ^ 8'd92);

assign xor_ln132_7_fu_403_p2 = (tmp_8_fu_389_p3 ^ 8'd92);

assign xor_ln132_8_fu_423_p2 = (tmp_9_fu_409_p3 ^ 8'd92);

assign xor_ln132_9_fu_443_p2 = (tmp_10_fu_429_p3 ^ 8'd92);

assign xor_ln132_fu_263_p2 = (tmp_s_fu_249_p3 ^ 8'd92);

endmodule //test_hmac_sha256_kpad_32_64_256_32_64_sha256_wrapper_s
