-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_hmac_sha256_hash is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mergeKipadStrm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    mergeKipadStrm_empty_n : IN STD_LOGIC;
    mergeKipadStrm_read : OUT STD_LOGIC;
    mergeKipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    mergeKipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    mergeKipadLenStrm_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    mergeKipadLenStrm_empty_n : IN STD_LOGIC;
    mergeKipadLenStrm_read : OUT STD_LOGIC;
    mergeKipadLenStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    mergeKipadLenStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    eMergeKipadLenStrm_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    eMergeKipadLenStrm_empty_n : IN STD_LOGIC;
    eMergeKipadLenStrm_read : OUT STD_LOGIC;
    eMergeKipadLenStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    eMergeKipadLenStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    msgHashStrm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    msgHashStrm_full_n : IN STD_LOGIC;
    msgHashStrm_write : OUT STD_LOGIC;
    msgHashStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    msgHashStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    eMsgHashStrm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    eMsgHashStrm_full_n : IN STD_LOGIC;
    eMsgHashStrm_write : OUT STD_LOGIC;
    eMsgHashStrm_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    eMsgHashStrm_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of test_hmac_sha256_hash is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_sha256_top_32_256_s_fu_32_mergeKopadStrm_read : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_mergeKopadLenStrm_read : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_eMergeKopadLenStrm_read : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_hshStrm_din : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_sha256_top_32_256_s_fu_32_hshStrm_write : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_eHshStrm_din : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_sha256_top_32_256_s_fu_32_eHshStrm_write : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_ap_start : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_ap_done : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_ap_ready : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_ap_idle : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_ap_continue : STD_LOGIC;
    signal grp_sha256_top_32_256_s_fu_32_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call10 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done : STD_LOGIC := '0';
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_sync_grp_sha256_top_32_256_s_fu_32_ap_ready : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_hmac_sha256_sha256_top_32_256_s IS
    port (
        mergeKopadStrm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        mergeKopadStrm_empty_n : IN STD_LOGIC;
        mergeKopadStrm_read : OUT STD_LOGIC;
        mergeKopadLenStrm_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        mergeKopadLenStrm_empty_n : IN STD_LOGIC;
        mergeKopadLenStrm_read : OUT STD_LOGIC;
        eMergeKopadLenStrm_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        eMergeKopadLenStrm_empty_n : IN STD_LOGIC;
        eMergeKopadLenStrm_read : OUT STD_LOGIC;
        hshStrm_din : OUT STD_LOGIC_VECTOR (255 downto 0);
        hshStrm_full_n : IN STD_LOGIC;
        hshStrm_write : OUT STD_LOGIC;
        eHshStrm_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        eHshStrm_full_n : IN STD_LOGIC;
        eHshStrm_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    grp_sha256_top_32_256_s_fu_32 : component test_hmac_sha256_sha256_top_32_256_s
    port map (
        mergeKopadStrm_dout => mergeKipadStrm_dout,
        mergeKopadStrm_empty_n => mergeKipadStrm_empty_n,
        mergeKopadStrm_read => grp_sha256_top_32_256_s_fu_32_mergeKopadStrm_read,
        mergeKopadLenStrm_dout => mergeKipadLenStrm_dout,
        mergeKopadLenStrm_empty_n => mergeKipadLenStrm_empty_n,
        mergeKopadLenStrm_read => grp_sha256_top_32_256_s_fu_32_mergeKopadLenStrm_read,
        eMergeKopadLenStrm_dout => eMergeKipadLenStrm_dout,
        eMergeKopadLenStrm_empty_n => eMergeKipadLenStrm_empty_n,
        eMergeKopadLenStrm_read => grp_sha256_top_32_256_s_fu_32_eMergeKopadLenStrm_read,
        hshStrm_din => grp_sha256_top_32_256_s_fu_32_hshStrm_din,
        hshStrm_full_n => msgHashStrm_full_n,
        hshStrm_write => grp_sha256_top_32_256_s_fu_32_hshStrm_write,
        eHshStrm_din => grp_sha256_top_32_256_s_fu_32_eHshStrm_din,
        eHshStrm_full_n => eMsgHashStrm_full_n,
        eHshStrm_write => grp_sha256_top_32_256_s_fu_32_eHshStrm_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sha256_top_32_256_s_fu_32_ap_start,
        ap_done => grp_sha256_top_32_256_s_fu_32_ap_done,
        ap_ready => grp_sha256_top_32_256_s_fu_32_ap_ready,
        ap_idle => grp_sha256_top_32_256_s_fu_32_ap_idle,
        ap_continue => grp_sha256_top_32_256_s_fu_32_ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done <= ap_const_logic_0;
                elsif ((grp_sha256_top_32_256_s_fu_32_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready <= ap_const_logic_0;
                elsif ((grp_sha256_top_32_256_s_fu_32_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_top_32_256_s_fu_32_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sha256_top_32_256_s_fu_32_ap_start_reg <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_state1_ignore_call10) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_sync_grp_sha256_top_32_256_s_fu_32_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
                    grp_sha256_top_32_256_s_fu_32_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_top_32_256_s_fu_32_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_top_32_256_s_fu_32_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call10_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call10 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready, ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready and ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_sync_grp_sha256_top_32_256_s_fu_32_ap_ready <= (grp_sha256_top_32_256_s_fu_32_ap_ready or ap_sync_reg_grp_sha256_top_32_256_s_fu_32_ap_ready);
    eMergeKipadLenStrm_read <= grp_sha256_top_32_256_s_fu_32_eMergeKopadLenStrm_read;
    eMsgHashStrm_din <= grp_sha256_top_32_256_s_fu_32_eHshStrm_din;
    eMsgHashStrm_write <= grp_sha256_top_32_256_s_fu_32_eHshStrm_write;

    grp_sha256_top_32_256_s_fu_32_ap_continue_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            grp_sha256_top_32_256_s_fu_32_ap_continue <= ap_const_logic_1;
        else 
            grp_sha256_top_32_256_s_fu_32_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_sha256_top_32_256_s_fu_32_ap_start <= grp_sha256_top_32_256_s_fu_32_ap_start_reg;
    mergeKipadLenStrm_read <= grp_sha256_top_32_256_s_fu_32_mergeKopadLenStrm_read;
    mergeKipadStrm_read <= grp_sha256_top_32_256_s_fu_32_mergeKopadStrm_read;
    msgHashStrm_din <= grp_sha256_top_32_256_s_fu_32_hshStrm_din;
    msgHashStrm_write <= grp_sha256_top_32_256_s_fu_32_hshStrm_write;
end behav;
