-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_empty_n : IN STD_LOGIC;
    inStream_read : OUT STD_LOGIC;
    compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    compressdStream_full_n : IN STD_LOGIC;
    compressdStream_write : OUT STD_LOGIC;
    compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    input_size : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size_c2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    input_size_c2_full_n : IN STD_LOGIC;
    input_size_c2_write : OUT STD_LOGIC;
    input_size_c2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    input_size_c2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv24_FFFFC0 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal inStream_blk_n : STD_LOGIC;
    signal icmp_ln63_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal compressdStream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal input_size_c2_blk_n : STD_LOGIC;
    signal icmp_ln63_reg_250 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal inStream_read_reg_254 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln87_fu_140_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln87_reg_259 : STD_LOGIC_VECTOR (23 downto 0);
    signal inStream_read_1_reg_264 : STD_LOGIC_VECTOR (7 downto 0);
    signal inStream_read_2_reg_269 : STD_LOGIC_VECTOR (7 downto 0);
    signal inStream_read_3_reg_274 : STD_LOGIC_VECTOR (7 downto 0);
    signal inStream_read_4_reg_279 : STD_LOGIC_VECTOR (7 downto 0);
    signal boundary_fu_144_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal boundary_reg_284 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_4_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_3_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_2_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_1_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal zext_ln187_fu_167_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln187_1_fu_175_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln187_2_fu_183_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln187_3_fu_191_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln187_4_fu_199_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state14_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        empty_11 : IN STD_LOGIC_VECTOR (7 downto 0);
        empty_12 : IN STD_LOGIC_VECTOR (7 downto 0);
        empty_13 : IN STD_LOGIC_VECTOR (7 downto 0);
        empty_14 : IN STD_LOGIC_VECTOR (7 downto 0);
        empty : IN STD_LOGIC_VECTOR (7 downto 0);
        boundary : IN STD_LOGIC_VECTOR (23 downto 0);
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        outValue_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outValue_4_out_ap_vld : OUT STD_LOGIC;
        outValue_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outValue_3_out_ap_vld : OUT STD_LOGIC;
        outValue_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outValue_2_out_ap_vld : OUT STD_LOGIC;
        outValue_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outValue_1_out_ap_vld : OUT STD_LOGIC;
        outValue_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        outValue_out_ap_vld : OUT STD_LOGIC );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_ready,
        empty_11 => inStream_read_4_reg_279,
        empty_12 => inStream_read_3_reg_274,
        empty_13 => inStream_read_2_reg_269,
        empty_14 => inStream_read_1_reg_264,
        empty => inStream_read_reg_254,
        boundary => boundary_reg_284,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_inStream_read,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_write,
        compressdStream_num_data_valid => ap_const_lv4_0,
        compressdStream_fifo_cap => ap_const_lv4_0,
        outValue_4_out => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_4_out,
        outValue_4_out_ap_vld => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_4_out_ap_vld,
        outValue_3_out => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_3_out,
        outValue_3_out_ap_vld => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_3_out_ap_vld,
        outValue_2_out => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_2_out,
        outValue_2_out_ap_vld => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_2_out_ap_vld,
        outValue_1_out => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_1_out,
        outValue_1_out_ap_vld => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_1_out_ap_vld,
        outValue_out => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_out,
        outValue_out_ap_vld => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_out_ap_vld);

    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_ready,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_inStream_read,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_write,
        compressdStream_num_data_valid => ap_const_lv4_0,
        compressdStream_fifo_cap => ap_const_lv4_0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_boolean_0 = ap_block_state14_on_subcall_done))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                boundary_reg_284 <= boundary_fu_144_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                icmp_ln63_reg_250 <= icmp_ln63_fu_134_p2;
                inStream_read_reg_254 <= inStream_dout;
                trunc_ln87_reg_259 <= trunc_ln87_fu_140_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                inStream_read_1_reg_264 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                inStream_read_2_reg_269 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                inStream_read_3_reg_274 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                inStream_read_4_reg_279 <= inStream_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, inStream_empty_n, compressdStream_full_n, icmp_ln63_fu_134_p2, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_block_state1, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_done, ap_CS_fsm_state7, ap_CS_fsm_state14, ap_block_state14_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln63_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif (((icmp_ln63_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_boolean_0 = ap_block_state14_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(compressdStream_full_n)
    begin
        if ((compressdStream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state11_blk_assign_proc : process(compressdStream_full_n)
    begin
        if ((compressdStream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state12_blk_assign_proc : process(compressdStream_full_n)
    begin
        if ((compressdStream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(ap_block_state14_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state14_on_subcall_done)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(inStream_empty_n)
    begin
        if ((inStream_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(inStream_empty_n)
    begin
        if ((inStream_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(inStream_empty_n)
    begin
        if ((inStream_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(inStream_empty_n)
    begin
        if ((inStream_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_done)
    begin
        if ((grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(compressdStream_full_n)
    begin
        if ((compressdStream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(compressdStream_full_n)
    begin
        if ((compressdStream_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, inStream_empty_n, input_size_c2_full_n, icmp_ln63_fu_134_p2)
    begin
                ap_block_state1 <= ((input_size_c2_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((icmp_ln63_fu_134_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state14_on_subcall_done_assign_proc : process(icmp_ln63_reg_250, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_done)
    begin
                ap_block_state14_on_subcall_done <= ((grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_done = ap_const_logic_0) and (icmp_ln63_reg_250 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state14, ap_block_state14_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_boolean_0 = ap_block_state14_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    boundary_fu_144_p2 <= std_logic_vector(unsigned(trunc_ln87_reg_259) + unsigned(ap_const_lv24_FFFFC0));

    compressdStream_blk_n_assign_proc : process(compressdStream_full_n, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            compressdStream_blk_n <= compressdStream_full_n;
        else 
            compressdStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    compressdStream_din_assign_proc : process(compressdStream_full_n, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, icmp_ln63_reg_250, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_din, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_din, ap_CS_fsm_state7, ap_CS_fsm_state14, zext_ln187_fu_167_p1, zext_ln187_1_fu_175_p1, zext_ln187_2_fu_183_p1, zext_ln187_3_fu_191_p1, zext_ln187_4_fu_199_p1)
    begin
        if (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            compressdStream_din <= zext_ln187_4_fu_199_p1;
        elsif (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            compressdStream_din <= zext_ln187_3_fu_191_p1;
        elsif (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            compressdStream_din <= zext_ln187_2_fu_183_p1;
        elsif (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            compressdStream_din <= zext_ln187_1_fu_175_p1;
        elsif (((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            compressdStream_din <= zext_ln187_fu_167_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln63_reg_250 = ap_const_lv1_0))) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_din;
        else 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_din;
        end if; 
    end process;


    compressdStream_write_assign_proc : process(compressdStream_full_n, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, icmp_ln63_reg_250, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_write, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_write, ap_CS_fsm_state7, ap_CS_fsm_state14)
    begin
        if ((((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9)) or ((compressdStream_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8)))) then 
            compressdStream_write <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln63_reg_250 = ap_const_lv1_0))) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_compressdStream_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_compressdStream_write;
        else 
            compressdStream_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_ap_start_reg;
    icmp_ln63_fu_134_p2 <= "1" when (input_size = ap_const_lv32_0) else "0";

    inStream_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, inStream_empty_n, icmp_ln63_fu_134_p2, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (icmp_ln63_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            inStream_blk_n <= inStream_empty_n;
        else 
            inStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    inStream_read_assign_proc : process(ap_CS_fsm_state1, inStream_empty_n, icmp_ln63_fu_134_p2, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, icmp_ln63_reg_250, ap_block_state1, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_inStream_read, grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_inStream_read, ap_CS_fsm_state7, ap_CS_fsm_state14)
    begin
        if ((((icmp_ln63_fu_134_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            inStream_read <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (icmp_ln63_reg_250 = ap_const_lv1_0))) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_lz_left_bytes_fu_126_inStream_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_inStream_read;
        else 
            inStream_read <= ap_const_logic_0;
        end if; 
    end process;


    input_size_c2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, input_size_c2_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_c2_blk_n <= input_size_c2_full_n;
        else 
            input_size_c2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_size_c2_din <= input_size;

    input_size_c2_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            input_size_c2_write <= ap_const_logic_1;
        else 
            input_size_c2_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state14, ap_block_state14_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (ap_const_boolean_0 = ap_block_state14_on_subcall_done))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln87_fu_140_p1 <= input_size(24 - 1 downto 0);
    zext_ln187_1_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_1_out),32));
    zext_ln187_2_fu_183_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_2_out),32));
    zext_ln187_3_fu_191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_3_out),32));
    zext_ln187_4_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_4_out),32));
    zext_ln187_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_lzCompress_6_4_65536_6_1_4096_64_Pipeline_VITIS_LOOP_88_2_fu_105_outValue_out),32));
end behav;
