-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_hmac_sha256_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    keyStrm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    keyStrm_empty_n : IN STD_LOGIC;
    keyStrm_read : OUT STD_LOGIC;
    k1_out : OUT STD_LOGIC_VECTOR (511 downto 0);
    k1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of test_hmac_sha256_kpad_32_64_256_32_64_sha256_wrapper_Pipeline_VITIS_LOOP_120_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln120_fu_80_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal keyStrm_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal k1_fu_46 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal k1_1_fu_114_p5 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal i_02_fu_50 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_8_fu_86_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal tmp_s_fu_100_p4 : STD_LOGIC_VECTOR (223 downto 0);
    signal trunc_ln124_fu_110_p1 : STD_LOGIC_VECTOR (223 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component test_hmac_sha256_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component test_hmac_sha256_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_02_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln120_fu_80_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_02_fu_50 <= i_8_fu_86_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_02_fu_50 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    k1_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k1_fu_46(256) <= '0';
                    k1_fu_46(257) <= '0';
                    k1_fu_46(258) <= '0';
                    k1_fu_46(259) <= '0';
                    k1_fu_46(260) <= '0';
                    k1_fu_46(261) <= '0';
                    k1_fu_46(262) <= '0';
                    k1_fu_46(263) <= '0';
                    k1_fu_46(264) <= '0';
                    k1_fu_46(265) <= '0';
                    k1_fu_46(266) <= '0';
                    k1_fu_46(267) <= '0';
                    k1_fu_46(268) <= '0';
                    k1_fu_46(269) <= '0';
                    k1_fu_46(270) <= '0';
                    k1_fu_46(271) <= '0';
                    k1_fu_46(272) <= '0';
                    k1_fu_46(273) <= '0';
                    k1_fu_46(274) <= '0';
                    k1_fu_46(275) <= '0';
                    k1_fu_46(276) <= '0';
                    k1_fu_46(277) <= '0';
                    k1_fu_46(278) <= '0';
                    k1_fu_46(279) <= '0';
                    k1_fu_46(280) <= '0';
                    k1_fu_46(281) <= '0';
                    k1_fu_46(282) <= '0';
                    k1_fu_46(283) <= '0';
                    k1_fu_46(284) <= '0';
                    k1_fu_46(285) <= '0';
                    k1_fu_46(286) <= '0';
                    k1_fu_46(287) <= '0';
                    k1_fu_46(288) <= '0';
                    k1_fu_46(289) <= '0';
                    k1_fu_46(290) <= '0';
                    k1_fu_46(291) <= '0';
                    k1_fu_46(292) <= '0';
                    k1_fu_46(293) <= '0';
                    k1_fu_46(294) <= '0';
                    k1_fu_46(295) <= '0';
                    k1_fu_46(296) <= '0';
                    k1_fu_46(297) <= '0';
                    k1_fu_46(298) <= '0';
                    k1_fu_46(299) <= '0';
                    k1_fu_46(300) <= '0';
                    k1_fu_46(301) <= '0';
                    k1_fu_46(302) <= '0';
                    k1_fu_46(303) <= '0';
                    k1_fu_46(304) <= '0';
                    k1_fu_46(305) <= '0';
                    k1_fu_46(306) <= '0';
                    k1_fu_46(307) <= '0';
                    k1_fu_46(308) <= '0';
                    k1_fu_46(309) <= '0';
                    k1_fu_46(310) <= '0';
                    k1_fu_46(311) <= '0';
                    k1_fu_46(312) <= '0';
                    k1_fu_46(313) <= '0';
                    k1_fu_46(314) <= '0';
                    k1_fu_46(315) <= '0';
                    k1_fu_46(316) <= '0';
                    k1_fu_46(317) <= '0';
                    k1_fu_46(318) <= '0';
                    k1_fu_46(319) <= '0';
                    k1_fu_46(320) <= '0';
                    k1_fu_46(321) <= '0';
                    k1_fu_46(322) <= '0';
                    k1_fu_46(323) <= '0';
                    k1_fu_46(324) <= '0';
                    k1_fu_46(325) <= '0';
                    k1_fu_46(326) <= '0';
                    k1_fu_46(327) <= '0';
                    k1_fu_46(328) <= '0';
                    k1_fu_46(329) <= '0';
                    k1_fu_46(330) <= '0';
                    k1_fu_46(331) <= '0';
                    k1_fu_46(332) <= '0';
                    k1_fu_46(333) <= '0';
                    k1_fu_46(334) <= '0';
                    k1_fu_46(335) <= '0';
                    k1_fu_46(336) <= '0';
                    k1_fu_46(337) <= '0';
                    k1_fu_46(338) <= '0';
                    k1_fu_46(339) <= '0';
                    k1_fu_46(340) <= '0';
                    k1_fu_46(341) <= '0';
                    k1_fu_46(342) <= '0';
                    k1_fu_46(343) <= '0';
                    k1_fu_46(344) <= '0';
                    k1_fu_46(345) <= '0';
                    k1_fu_46(346) <= '0';
                    k1_fu_46(347) <= '0';
                    k1_fu_46(348) <= '0';
                    k1_fu_46(349) <= '0';
                    k1_fu_46(350) <= '0';
                    k1_fu_46(351) <= '0';
                    k1_fu_46(352) <= '0';
                    k1_fu_46(353) <= '0';
                    k1_fu_46(354) <= '0';
                    k1_fu_46(355) <= '0';
                    k1_fu_46(356) <= '0';
                    k1_fu_46(357) <= '0';
                    k1_fu_46(358) <= '0';
                    k1_fu_46(359) <= '0';
                    k1_fu_46(360) <= '0';
                    k1_fu_46(361) <= '0';
                    k1_fu_46(362) <= '0';
                    k1_fu_46(363) <= '0';
                    k1_fu_46(364) <= '0';
                    k1_fu_46(365) <= '0';
                    k1_fu_46(366) <= '0';
                    k1_fu_46(367) <= '0';
                    k1_fu_46(368) <= '0';
                    k1_fu_46(369) <= '0';
                    k1_fu_46(370) <= '0';
                    k1_fu_46(371) <= '0';
                    k1_fu_46(372) <= '0';
                    k1_fu_46(373) <= '0';
                    k1_fu_46(374) <= '0';
                    k1_fu_46(375) <= '0';
                    k1_fu_46(376) <= '0';
                    k1_fu_46(377) <= '0';
                    k1_fu_46(378) <= '0';
                    k1_fu_46(379) <= '0';
                    k1_fu_46(380) <= '0';
                    k1_fu_46(381) <= '0';
                    k1_fu_46(382) <= '0';
                    k1_fu_46(383) <= '0';
                    k1_fu_46(384) <= '0';
                    k1_fu_46(385) <= '0';
                    k1_fu_46(386) <= '0';
                    k1_fu_46(387) <= '0';
                    k1_fu_46(388) <= '0';
                    k1_fu_46(389) <= '0';
                    k1_fu_46(390) <= '0';
                    k1_fu_46(391) <= '0';
                    k1_fu_46(392) <= '0';
                    k1_fu_46(393) <= '0';
                    k1_fu_46(394) <= '0';
                    k1_fu_46(395) <= '0';
                    k1_fu_46(396) <= '0';
                    k1_fu_46(397) <= '0';
                    k1_fu_46(398) <= '0';
                    k1_fu_46(399) <= '0';
                    k1_fu_46(400) <= '0';
                    k1_fu_46(401) <= '0';
                    k1_fu_46(402) <= '0';
                    k1_fu_46(403) <= '0';
                    k1_fu_46(404) <= '0';
                    k1_fu_46(405) <= '0';
                    k1_fu_46(406) <= '0';
                    k1_fu_46(407) <= '0';
                    k1_fu_46(408) <= '0';
                    k1_fu_46(409) <= '0';
                    k1_fu_46(410) <= '0';
                    k1_fu_46(411) <= '0';
                    k1_fu_46(412) <= '0';
                    k1_fu_46(413) <= '0';
                    k1_fu_46(414) <= '0';
                    k1_fu_46(415) <= '0';
                    k1_fu_46(416) <= '0';
                    k1_fu_46(417) <= '0';
                    k1_fu_46(418) <= '0';
                    k1_fu_46(419) <= '0';
                    k1_fu_46(420) <= '0';
                    k1_fu_46(421) <= '0';
                    k1_fu_46(422) <= '0';
                    k1_fu_46(423) <= '0';
                    k1_fu_46(424) <= '0';
                    k1_fu_46(425) <= '0';
                    k1_fu_46(426) <= '0';
                    k1_fu_46(427) <= '0';
                    k1_fu_46(428) <= '0';
                    k1_fu_46(429) <= '0';
                    k1_fu_46(430) <= '0';
                    k1_fu_46(431) <= '0';
                    k1_fu_46(432) <= '0';
                    k1_fu_46(433) <= '0';
                    k1_fu_46(434) <= '0';
                    k1_fu_46(435) <= '0';
                    k1_fu_46(436) <= '0';
                    k1_fu_46(437) <= '0';
                    k1_fu_46(438) <= '0';
                    k1_fu_46(439) <= '0';
                    k1_fu_46(440) <= '0';
                    k1_fu_46(441) <= '0';
                    k1_fu_46(442) <= '0';
                    k1_fu_46(443) <= '0';
                    k1_fu_46(444) <= '0';
                    k1_fu_46(445) <= '0';
                    k1_fu_46(446) <= '0';
                    k1_fu_46(447) <= '0';
                    k1_fu_46(448) <= '0';
                    k1_fu_46(449) <= '0';
                    k1_fu_46(450) <= '0';
                    k1_fu_46(451) <= '0';
                    k1_fu_46(452) <= '0';
                    k1_fu_46(453) <= '0';
                    k1_fu_46(454) <= '0';
                    k1_fu_46(455) <= '0';
                    k1_fu_46(456) <= '0';
                    k1_fu_46(457) <= '0';
                    k1_fu_46(458) <= '0';
                    k1_fu_46(459) <= '0';
                    k1_fu_46(460) <= '0';
                    k1_fu_46(461) <= '0';
                    k1_fu_46(462) <= '0';
                    k1_fu_46(463) <= '0';
                    k1_fu_46(464) <= '0';
                    k1_fu_46(465) <= '0';
                    k1_fu_46(466) <= '0';
                    k1_fu_46(467) <= '0';
                    k1_fu_46(468) <= '0';
                    k1_fu_46(469) <= '0';
                    k1_fu_46(470) <= '0';
                    k1_fu_46(471) <= '0';
                    k1_fu_46(472) <= '0';
                    k1_fu_46(473) <= '0';
                    k1_fu_46(474) <= '0';
                    k1_fu_46(475) <= '0';
                    k1_fu_46(476) <= '0';
                    k1_fu_46(477) <= '0';
                    k1_fu_46(478) <= '0';
                    k1_fu_46(479) <= '0';
                    k1_fu_46(480) <= '0';
                    k1_fu_46(481) <= '0';
                    k1_fu_46(482) <= '0';
                    k1_fu_46(483) <= '0';
                    k1_fu_46(484) <= '0';
                    k1_fu_46(485) <= '0';
                    k1_fu_46(486) <= '0';
                    k1_fu_46(487) <= '0';
                    k1_fu_46(488) <= '0';
                    k1_fu_46(489) <= '0';
                    k1_fu_46(490) <= '0';
                    k1_fu_46(491) <= '0';
                    k1_fu_46(492) <= '0';
                    k1_fu_46(493) <= '0';
                    k1_fu_46(494) <= '0';
                    k1_fu_46(495) <= '0';
                    k1_fu_46(496) <= '0';
                    k1_fu_46(497) <= '0';
                    k1_fu_46(498) <= '0';
                    k1_fu_46(499) <= '0';
                    k1_fu_46(500) <= '0';
                    k1_fu_46(501) <= '0';
                    k1_fu_46(502) <= '0';
                    k1_fu_46(503) <= '0';
                    k1_fu_46(504) <= '0';
                    k1_fu_46(505) <= '0';
                    k1_fu_46(506) <= '0';
                    k1_fu_46(507) <= '0';
                    k1_fu_46(508) <= '0';
                    k1_fu_46(509) <= '0';
                    k1_fu_46(510) <= '0';
                    k1_fu_46(511) <= '0';
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                                        k1_fu_46(511 downto 256) <= k1_1_fu_114_p5(511 downto 256);
                end if;
            end if; 
        end if;
    end process;
    k1_fu_46(255 downto 0) <= "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, keyStrm_empty_n)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((keyStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, keyStrm_empty_n)
    begin
                ap_block_pp0_stage0_11001 <= ((keyStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, keyStrm_empty_n)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((keyStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, keyStrm_empty_n)
    begin
                ap_block_pp0_stage0_subdone <= ((keyStrm_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln120_fu_80_p2)
    begin
        if (((icmp_ln120_fu_80_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, i_02_fu_50, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i <= i_02_fu_50;
        end if; 
    end process;

    i_8_fu_86_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv4_1));
    icmp_ln120_fu_80_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv4_8) else "0";
    k1_1_fu_114_p5 <= (((tmp_s_fu_100_p4 & keyStrm_dout) & trunc_ln124_fu_110_p1) & ap_const_lv32_0);
    k1_out <= k1_fu_46;

    k1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln120_fu_80_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln120_fu_80_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            k1_out_ap_vld <= ap_const_logic_1;
        else 
            k1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    keyStrm_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, keyStrm_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            keyStrm_blk_n <= keyStrm_empty_n;
        else 
            keyStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    keyStrm_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            keyStrm_read <= ap_const_logic_1;
        else 
            keyStrm_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_100_p4 <= k1_fu_46(479 downto 256);
    trunc_ln124_fu_110_p1 <= k1_fu_46(224 - 1 downto 0);
end behav;
