-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mergeKipadStrm_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    mergeKipadStrm_empty_n : IN STD_LOGIC;
    mergeKipadStrm_read : OUT STD_LOGIC;
    mergeKipadStrm_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    mergeKipadStrm_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    p_cast : IN STD_LOGIC_VECTOR (3 downto 0);
    len : IN STD_LOGIC_VECTOR (1 downto 0);
    b_16_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_16_out_ap_vld : OUT STD_LOGIC;
    b_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_15_out_ap_vld : OUT STD_LOGIC;
    b_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_14_out_ap_vld : OUT STD_LOGIC;
    b_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_13_out_ap_vld : OUT STD_LOGIC;
    b_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_12_out_ap_vld : OUT STD_LOGIC;
    b_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_11_out_ap_vld : OUT STD_LOGIC;
    b_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_10_out_ap_vld : OUT STD_LOGIC;
    b_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_9_out_ap_vld : OUT STD_LOGIC;
    b_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_8_out_ap_vld : OUT STD_LOGIC;
    b_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_7_out_ap_vld : OUT STD_LOGIC;
    b_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_6_out_ap_vld : OUT STD_LOGIC;
    b_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_5_out_ap_vld : OUT STD_LOGIC;
    b_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_4_out_ap_vld : OUT STD_LOGIC;
    b_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of test_hmac_sha256_preProcessing_Pipeline_LOOP_SHA256_GEN_COPY_TAIL_AND_ONE is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln162_reg_1071 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_reg_1075 : STD_LOGIC_VECTOR (0 downto 0);
    signal len_read_reg_1060 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_predicate_op46_read_state2 : BOOLEAN;
    signal ap_predicate_op78_read_state2 : BOOLEAN;
    signal ap_predicate_op137_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln160_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal mergeKipadStrm_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal i_1_reg_1064 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln162_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln170_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_134 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln160_fu_344_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal b_fu_138 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_2_fu_371_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_1_fu_455_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_18_fu_607_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_27_fu_768_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_16_fu_142 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_4_fu_146 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_5_fu_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_6_fu_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_7_fu_158 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_8_fu_162 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_9_fu_166 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_10_fu_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_11_fu_174 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_12_fu_178 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_13_fu_182 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_14_fu_186 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal b_15_fu_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal trunc_ln187_fu_367_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_310_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln181_fu_451_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln192_fu_603_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_320_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_754_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_s_fu_758_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_45 : BOOLEAN;
    signal ap_condition_51 : BOOLEAN;
    signal ap_condition_176 : BOOLEAN;
    signal ap_condition_58 : BOOLEAN;
    signal ap_condition_649 : BOOLEAN;
    signal ap_condition_664 : BOOLEAN;
    signal ap_condition_667 : BOOLEAN;
    signal ap_condition_670 : BOOLEAN;
    signal ap_condition_673 : BOOLEAN;
    signal ap_condition_676 : BOOLEAN;
    signal ap_condition_208 : BOOLEAN;
    signal ap_condition_216 : BOOLEAN;
    signal ap_condition_223 : BOOLEAN;
    signal ap_condition_230 : BOOLEAN;
    signal ap_condition_241 : BOOLEAN;
    signal ap_condition_165 : BOOLEAN;
    signal ap_condition_691 : BOOLEAN;
    signal ap_condition_694 : BOOLEAN;
    signal ap_condition_697 : BOOLEAN;
    signal ap_condition_700 : BOOLEAN;
    signal ap_condition_703 : BOOLEAN;
    signal ap_condition_706 : BOOLEAN;
    signal ap_condition_167 : BOOLEAN;
    signal ap_condition_171 : BOOLEAN;
    signal ap_condition_177 : BOOLEAN;
    signal ap_condition_180 : BOOLEAN;
    signal ap_condition_195 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component test_hmac_sha256_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component test_hmac_sha256_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    b_10_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_649)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_10_fu_170 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_10_fu_170 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_10_fu_170 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_10_fu_170 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_10_fu_170 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_10_fu_170 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_11_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_664)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_11_fu_174 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_11_fu_174 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_11_fu_174 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_11_fu_174 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_11_fu_174 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_11_fu_174 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_12_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_667)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_12_fu_178 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_12_fu_178 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_12_fu_178 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_12_fu_178 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_12_fu_178 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_12_fu_178 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_13_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_670)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_13_fu_182 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_13_fu_182 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_13_fu_182 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_13_fu_182 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_13_fu_182 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_13_fu_182 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_14_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_673)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_14_fu_186 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_14_fu_186 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_14_fu_186 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_14_fu_186 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_14_fu_186 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_14_fu_186 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_15_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_676)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_15_fu_190 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_15_fu_190 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_15_fu_190 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_15_fu_190 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_15_fu_190 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_15_fu_190 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_16_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_165)) then
                if ((ap_const_boolean_1 = ap_condition_241)) then 
                    b_16_fu_142(7) <= '0';
                    b_16_fu_142(8) <= '0';
                    b_16_fu_142(9) <= '0';
                    b_16_fu_142(10) <= '0';
                    b_16_fu_142(11) <= '0';
                    b_16_fu_142(12) <= '0';
                    b_16_fu_142(13) <= '0';
                    b_16_fu_142(14) <= '0';
                    b_16_fu_142(15) <= '0';
                    b_16_fu_142(16) <= '0';
                    b_16_fu_142(17) <= '0';
                    b_16_fu_142(18) <= '0';
                    b_16_fu_142(19) <= '0';
                    b_16_fu_142(20) <= '0';
                    b_16_fu_142(21) <= '0';
                    b_16_fu_142(22) <= '0';
                    b_16_fu_142(23) <= '0';
                    b_16_fu_142(24) <= '0';
                    b_16_fu_142(25) <= '0';
                    b_16_fu_142(26) <= '0';
                    b_16_fu_142(27) <= '0';
                    b_16_fu_142(28) <= '0';
                    b_16_fu_142(29) <= '0';
                    b_16_fu_142(30) <= '0';
                    b_16_fu_142(31) <= '0';
                elsif ((ap_const_boolean_1 = ap_condition_230)) then 
                                        b_16_fu_142(31 downto 7) <= b_18_fu_607_p5(31 downto 7);
                elsif ((ap_const_boolean_1 = ap_condition_223)) then 
                    b_16_fu_142(7) <= '0';
                    b_16_fu_142(8) <= '0';
                    b_16_fu_142(9) <= '0';
                    b_16_fu_142(10) <= '0';
                    b_16_fu_142(11) <= '0';
                    b_16_fu_142(12) <= '0';
                    b_16_fu_142(13) <= '0';
                    b_16_fu_142(14) <= '0';
                    b_16_fu_142(15) <= '0';
                    b_16_fu_142(16) <= '0';
                    b_16_fu_142(17) <= '0';
                    b_16_fu_142(18) <= '0';
                    b_16_fu_142(19) <= '0';
                    b_16_fu_142(20) <= '0';
                    b_16_fu_142(21) <= '0';
                    b_16_fu_142(22) <= '0';
                    b_16_fu_142(23) <= '0';
                    b_16_fu_142(24) <= '0';
                    b_16_fu_142(25) <= '0';
                    b_16_fu_142(26) <= '0';
                    b_16_fu_142(27) <= '0';
                    b_16_fu_142(28) <= '0';
                    b_16_fu_142(29) <= '0';
                    b_16_fu_142(30) <= '0';
                    b_16_fu_142(31) <= '1';
                elsif ((ap_const_boolean_1 = ap_condition_216)) then 
                                        b_16_fu_142(31 downto 7) <= b_1_fu_455_p3(31 downto 7);
                elsif ((ap_const_boolean_1 = ap_condition_208)) then 
                                        b_16_fu_142(31 downto 7) <= b_2_fu_371_p4(31 downto 7);
                end if;
            end if; 
        end if;
    end process;

    b_4_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_691)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_4_fu_146 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_4_fu_146 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_4_fu_146 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_4_fu_146 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_4_fu_146 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_4_fu_146 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_5_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_694)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_5_fu_150 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_5_fu_150 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_5_fu_150 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_5_fu_150 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_5_fu_150 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_5_fu_150 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_6_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_697)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_6_fu_154 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_6_fu_154 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_6_fu_154 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_6_fu_154 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_6_fu_154 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_6_fu_154 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_7_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_700)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_7_fu_158 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_7_fu_158 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_7_fu_158 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_7_fu_158 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_7_fu_158 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_7_fu_158 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_8_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_703)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_8_fu_162 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_8_fu_162 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_8_fu_162 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_8_fu_162 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_8_fu_162 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_8_fu_162 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_9_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_706)) then
                if ((icmp_ln162_reg_1071 = ap_const_lv1_1)) then 
                    b_9_fu_166 <= l_27_fu_768_p5;
                elsif (((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0))) then 
                    b_9_fu_166 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_58)) then 
                    b_9_fu_166 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_176)) then 
                    b_9_fu_166 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_51)) then 
                    b_9_fu_166 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_45)) then 
                    b_9_fu_166 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    b_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_165)) then
                if ((ap_const_boolean_1 = ap_condition_195)) then 
                    b_fu_138 <= l_27_fu_768_p5;
                elsif ((ap_const_boolean_1 = ap_condition_180)) then 
                    b_fu_138 <= b_18_fu_607_p5;
                elsif ((ap_const_boolean_1 = ap_condition_177)) then 
                    b_fu_138 <= ap_const_lv32_80000000;
                elsif ((ap_const_boolean_1 = ap_condition_171)) then 
                    b_fu_138 <= b_1_fu_455_p3;
                elsif ((ap_const_boolean_1 = ap_condition_167)) then 
                    b_fu_138 <= b_2_fu_371_p4;
                end if;
            end if; 
        end if;
    end process;

    i_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln160_fu_338_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_134 <= add_ln160_fu_344_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_134 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_1_reg_1064 <= ap_sig_allocacmp_i_1;
                icmp_ln162_reg_1071 <= icmp_ln162_fu_350_p2;
                icmp_ln170_reg_1075 <= icmp_ln170_fu_356_p2;
            end if;
        end if;
    end process;
    b_16_fu_142(6 downto 0) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln160_fu_344_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;


    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(mergeKipadStrm_empty_n, icmp_ln162_reg_1071, ap_predicate_op46_read_state2, ap_predicate_op78_read_state2, ap_predicate_op137_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= (((icmp_ln162_reg_1071 = ap_const_lv1_1) and (mergeKipadStrm_empty_n = ap_const_logic_0)) or ((ap_predicate_op137_read_state2 = ap_const_boolean_1) and (mergeKipadStrm_empty_n = ap_const_logic_0)) or ((ap_predicate_op78_read_state2 = ap_const_boolean_1) and (mergeKipadStrm_empty_n = ap_const_logic_0)) or ((ap_predicate_op46_read_state2 = ap_const_boolean_1) and (mergeKipadStrm_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_165_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
                ap_condition_165 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_167_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len, i_1_reg_1064)
    begin
                ap_condition_167 <= ((len = ap_const_lv2_2) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_0));
    end process;


    ap_condition_171_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len, i_1_reg_1064)
    begin
                ap_condition_171 <= ((len = ap_const_lv2_1) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_0));
    end process;


    ap_condition_176_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len_read_reg_1060)
    begin
                ap_condition_176 <= ((len_read_reg_1060 = ap_const_lv2_0) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0));
    end process;


    ap_condition_177_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len_read_reg_1060, i_1_reg_1064)
    begin
                ap_condition_177 <= ((len_read_reg_1060 = ap_const_lv2_0) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_0));
    end process;


    ap_condition_180_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len, i_1_reg_1064)
    begin
                ap_condition_180 <= ((len = ap_const_lv2_3) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_0));
    end process;


    ap_condition_195_assign_proc : process(icmp_ln162_reg_1071, i_1_reg_1064)
    begin
                ap_condition_195 <= (((((icmp_ln162_reg_1071 = ap_const_lv1_1) and (i_1_reg_1064 = ap_const_lv4_E)) or ((icmp_ln162_reg_1071 = ap_const_lv1_1) and (i_1_reg_1064 = ap_const_lv4_F))) or ((icmp_ln162_reg_1071 = ap_const_lv1_1) and (i_1_reg_1064 = ap_const_lv4_D))) or ((icmp_ln162_reg_1071 = ap_const_lv1_1) and (i_1_reg_1064 = ap_const_lv4_0)));
    end process;


    ap_condition_208_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len, i_1_reg_1064)
    begin
                ap_condition_208 <= ((((len = ap_const_lv2_2) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_E)) or ((len = ap_const_lv2_2) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_F))) or ((len = ap_const_lv2_2) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_D)));
    end process;


    ap_condition_216_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len, i_1_reg_1064)
    begin
                ap_condition_216 <= ((((len = ap_const_lv2_1) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_E)) or ((len = ap_const_lv2_1) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_F))) or ((len = ap_const_lv2_1) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_D)));
    end process;


    ap_condition_223_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len_read_reg_1060, i_1_reg_1064)
    begin
                ap_condition_223 <= ((((len_read_reg_1060 = ap_const_lv2_0) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_E)) or ((len_read_reg_1060 = ap_const_lv2_0) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_F))) or ((len_read_reg_1060 = ap_const_lv2_0) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_D)));
    end process;


    ap_condition_230_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len, i_1_reg_1064)
    begin
                ap_condition_230 <= ((((len = ap_const_lv2_3) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_E)) or ((len = ap_const_lv2_3) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_F))) or ((len = ap_const_lv2_3) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_D)));
    end process;


    ap_condition_241_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, i_1_reg_1064)
    begin
                ap_condition_241 <= (((((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_E)) or ((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_F))) or ((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_D))) or ((icmp_ln170_reg_1075 = ap_const_lv1_1) and (icmp_ln162_reg_1071 = ap_const_lv1_0) and (i_1_reg_1064 = ap_const_lv4_0)));
    end process;


    ap_condition_45_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len)
    begin
                ap_condition_45 <= ((len = ap_const_lv2_2) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0));
    end process;


    ap_condition_51_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len)
    begin
                ap_condition_51 <= ((len = ap_const_lv2_1) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0));
    end process;


    ap_condition_58_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len)
    begin
                ap_condition_58 <= ((len = ap_const_lv2_3) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0));
    end process;


    ap_condition_649_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_649 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_7));
    end process;


    ap_condition_664_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_664 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_8));
    end process;


    ap_condition_667_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_667 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_9));
    end process;


    ap_condition_670_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_670 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_A));
    end process;


    ap_condition_673_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_673 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_B));
    end process;


    ap_condition_676_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_676 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_C));
    end process;


    ap_condition_691_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_691 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_1));
    end process;


    ap_condition_694_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_694 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_2));
    end process;


    ap_condition_697_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_697 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_3));
    end process;


    ap_condition_700_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_700 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_4));
    end process;


    ap_condition_703_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_703 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_5));
    end process;


    ap_condition_706_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1, i_1_reg_1064)
    begin
                ap_condition_706 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (i_1_reg_1064 = ap_const_lv4_6));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln160_fu_338_p2)
    begin
        if (((icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op137_read_state2_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len)
    begin
                ap_predicate_op137_read_state2 <= ((len = ap_const_lv2_3) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0));
    end process;


    ap_predicate_op46_read_state2_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len)
    begin
                ap_predicate_op46_read_state2 <= ((len = ap_const_lv2_2) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0));
    end process;


    ap_predicate_op78_read_state2_assign_proc : process(icmp_ln162_reg_1071, icmp_ln170_reg_1075, len)
    begin
                ap_predicate_op78_read_state2 <= ((len = ap_const_lv2_1) and (icmp_ln170_reg_1075 = ap_const_lv1_0) and (icmp_ln162_reg_1071 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_134, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_134;
        end if; 
    end process;

    b_10_out <= b_10_fu_170;

    b_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_10_out_ap_vld <= ap_const_logic_1;
        else 
            b_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_11_out <= b_11_fu_174;

    b_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_11_out_ap_vld <= ap_const_logic_1;
        else 
            b_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_12_out <= b_12_fu_178;

    b_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_12_out_ap_vld <= ap_const_logic_1;
        else 
            b_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_13_out <= b_13_fu_182;

    b_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_13_out_ap_vld <= ap_const_logic_1;
        else 
            b_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_14_out <= b_14_fu_186;

    b_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_14_out_ap_vld <= ap_const_logic_1;
        else 
            b_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_15_out <= b_15_fu_190;

    b_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_15_out_ap_vld <= ap_const_logic_1;
        else 
            b_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_16_out <= b_16_fu_142;

    b_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_16_out_ap_vld <= ap_const_logic_1;
        else 
            b_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_18_fu_607_p5 <= (((trunc_ln192_fu_603_p1 & grp_fu_310_p4) & grp_fu_320_p4) & ap_const_lv8_80);
    b_1_fu_455_p3 <= (trunc_ln181_fu_451_p1 & ap_const_lv24_800000);
    b_2_fu_371_p4 <= ((trunc_ln187_fu_367_p1 & grp_fu_310_p4) & ap_const_lv16_8000);
    b_4_out <= b_4_fu_146;

    b_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_4_out_ap_vld <= ap_const_logic_1;
        else 
            b_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_5_out <= b_5_fu_150;

    b_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_5_out_ap_vld <= ap_const_logic_1;
        else 
            b_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_6_out <= b_6_fu_154;

    b_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_6_out_ap_vld <= ap_const_logic_1;
        else 
            b_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_7_out <= b_7_fu_158;

    b_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_7_out_ap_vld <= ap_const_logic_1;
        else 
            b_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_8_out <= b_8_fu_162;

    b_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_8_out_ap_vld <= ap_const_logic_1;
        else 
            b_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_9_out <= b_9_fu_166;

    b_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_9_out_ap_vld <= ap_const_logic_1;
        else 
            b_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    b_out <= b_fu_138;

    b_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln160_fu_338_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln160_fu_338_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_out_ap_vld <= ap_const_logic_1;
        else 
            b_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_754_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    grp_fu_310_p4 <= mergeKipadStrm_dout(15 downto 8);
    grp_fu_320_p4 <= mergeKipadStrm_dout(23 downto 16);
    icmp_ln160_fu_338_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_E) else "0";
    icmp_ln162_fu_350_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) < unsigned(p_cast)) else "0";
    icmp_ln170_fu_356_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) > unsigned(p_cast)) else "0";
    l_27_fu_768_p5 <= (((empty_fu_754_p1 & grp_fu_310_p4) & grp_fu_320_p4) & p_s_fu_758_p4);
    len_read_reg_1060 <= len;

    mergeKipadStrm_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, mergeKipadStrm_empty_n, icmp_ln162_reg_1071, ap_predicate_op46_read_state2, ap_predicate_op78_read_state2, ap_predicate_op137_read_state2, ap_block_pp0_stage0_grp1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln162_reg_1071 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op137_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op78_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op46_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            mergeKipadStrm_blk_n <= mergeKipadStrm_empty_n;
        else 
            mergeKipadStrm_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    mergeKipadStrm_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln162_reg_1071, ap_predicate_op46_read_state2, ap_predicate_op78_read_state2, ap_predicate_op137_read_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln162_reg_1071 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op137_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op78_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op46_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            mergeKipadStrm_read <= ap_const_logic_1;
        else 
            mergeKipadStrm_read <= ap_const_logic_0;
        end if; 
    end process;

    p_s_fu_758_p4 <= mergeKipadStrm_dout(31 downto 24);
    trunc_ln181_fu_451_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    trunc_ln187_fu_367_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
    trunc_ln192_fu_603_p1 <= mergeKipadStrm_dout(8 - 1 downto 0);
end behav;
